<a href="https://colab.research.google.com/github/iTharindu/reasoning-withing-a-structure/blob/main/Notebooks/Model_Checking_Anaphora_Template_based.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
male_names = ['Liam', 'Noah', 'Oliver', 'William', 'Elijah', 'James', 'Benjamin', 'Lucas', 'Mason', 'Ethan', 'Alexander', 'Henry', 'Jacob', 'Michael', 'Daniel', 'Logan', 'Jackson', 'Sebastian', 'Jack', 'Aiden', 'Owen', 'Samuel', 'Matthew', 'Joseph', 'Levi', 'Mateo', 'David', 'John', 'Wyatt', 'Carter', 'Julian', 'Luke', 'Grayson', 'Isaac', 'Jayden', 'Theodore', 'Gabriel', 'Anthony', 'Dylan', 'Leo', 'Lincoln', 'Jaxon', 'Asher', 'Christopher', 'Josiah', 'Andrew', 'Thomas', 'Joshua', 'Ezra', 'Hudson', 'Charles', 'Caleb', 'Isaiah', 'Ryan', 'Nathan', 'Adrian', 'Christian', 'Maverick', 'Colton', 'Elias', 'Aaron', 'Eli', 'Landon', 'Jonathan', 'Nolan', 'Hunter', 'Cameron', 'Connor', 'Santiago', 'Jeremiah', 'Ezekiel', 'Angel', 'Roman', 'Easton', 'Miles', 'Robert', 'Jameson', 'Nicholas', 'Greyson', 'Cooper', 'Ian', 'Carson', 'Axel', 'Jaxson', 'Dominic', 'Leonardo', 'Luca', 'Austin', 'Jordan', 'Adam', 'Xavier', 'Jose', 'Jace', 'Everett', 'Declan', 'Evan', 'Kayden', 'Parker', 'Wesley', 'Kai', 'Brayden', 'Bryson', 'Weston', 'Jason', 'Emmett', 'Sawyer', 'Silas', 'Bennett', 'Brooks', 'Micah', 'Damian', 'Harrison', 'Waylon', 'Ayden', 'Vincent', 'Ryder', 'Kingston', 'Rowan', 'George', 'Luis', 'Chase', 'Cole', 'Nathaniel', 'Zachary', 'Ashton', 'Braxton', 'Gavin', 'Tyler', 'Diego', 'Bentley', 'Amir', 'Beau', 'Gael', 'Carlos', 'Ryker', 'Jasper', 'Max', 'Juan', 'Ivan', 'Brandon', 'Jonah', 'Giovanni', 'Kaiden', 'Myles', 'Calvin', 'Lorenzo', 'Maxwell', 'Jayce', 'Kevin', 'Legend', 'Tristan', 'Jesus', 'Jude', 'Zion', 'Justin', 'Maddox', 'Abel', 'King', 'Camden', 'Elliott', 'Malachi', 'Milo', 'Emmanuel', 'Karter', 'Rhett', 'Alex', 'August', 'River', 'Xander', 'Antonio', 'Brody', 'Finn', 'Elliot', 'Dean', 'Emiliano', 'Eric', 'Miguel', 'Arthur', 'Matteo', 'Graham', 'Alan', 'Nicolas', 'Blake', 'Thiago', 'Adriel', 'Victor', 'Joel', 'Timothy', 'Hayden', 'Judah', 'Abraham', 'Edward', 'Messiah', 'Zayden', 'Theo', 'Tucker', 'Grant', 'Richard', 'Alejandro', 'Steven', 'Jesse', 'Dawson', 'Bryce', 'Avery', 'Oscar', 'Patrick', 'Archer', 'Barrett', 'Leon', 'Colt', 'Charlie', 'Peter', 'Kaleb', 'Lukas', 'Beckett', 'Jeremy', 'Preston', 'Enzo', 'Luka', 'Andres', 'Marcus', 'Felix', 'Mark', 'Ace', 'Brantley', 'Atlas', 'Remington', 'Maximus', 'Matias', 'Walker', 'Kyrie', 'Griffin', 'Kenneth', 'Israel', 'Javier', 'Kyler', 'Jax', 'Amari', 'Zane', 'Emilio', 'Knox', 'Adonis', 'Aidan', 'Kaden', 'Paul', 'Omar', 'BrianPeter', 'Louis', 'Caden', 'Maximiliano', 'Holden', 'Paxton', 'Nash', 'Bradley', 'Bryan', 'Simon', 'Phoenix', 'Lane', 'Josue', 'Colin', 'Rafael', 'Kyle', 'Riley', 'Jorge', 'Beckham', 'Cayden', 'Jaden', 'Emerson', 'Ronan', 'Karson', 'Arlo', 'Tobias', 'Brady', 'Clayton', 'Francisco', 'Zander', 'Erick', 'Walter', 'Daxton', 'Martin', 'Damien', 'Dallas', 'Cody', 'Chance', 'Jensen', 'Finley', 'Jett', 'Corbin', 'Kash', 'Reid', 'Kameron', 'Andre', 'Gunner', 'Jake', 'Hayes', 'Manuel', 'Prince', 'Bodhi', 'Cohen', 'Sean', 'Khalil', 'Hendrix', 'Derek', 'Cristian', 'Cruz', 'Kairo', 'Dante', 'Atticus', 'Killian', 'Stephen', 'Orion', 'Malakai', 'Ali', 'Eduardo', 'Fernando', 'Anderson', 'Angelo', 'Spencer', 'Gideon', 'Mario', 'Titus', 'Travis', 'Rylan', 'Kayson', 'Ricardo', 'Tanner', 'Malcolm', 'Raymond', 'Odin', 'Cesar', 'Lennox', 'Joaquin', 'Kane', 'Wade', 'Muhammad', 'Iker', 'Jaylen', 'Crew', 'Zayn', 'Hector', 'Ellis', 'Leonel', 'Cairo', 'Garrett', 'Romeo', 'Dakota', 'Edwin', 'Warren', 'Julius', 'Major', 'Donovan', 'Caiden', 'Tyson', 'Nico', 'Sergio', 'Nasir', 'Rory', 'Devin', 'Jaiden', 'Jared', 'Kason', 'Malik', 'Jeffrey', 'Ismael', 'Elian', 'Marshall', 'Lawson', 'Desmond', 'Winston', 'Nehemiah', 'Ari', 'Conner', 'Jay', 'Kade', 'Andy', 'Johnny', 'Jayceon', 'Marco', 'Seth', 'Ibrahim', 'Raiden', 'Collin', 'Edgar', 'Erik', 'Troy', 'Clark', 'Jaxton', 'Johnathan', 'Gregory', 'Russell', 'Royce', 'Fabian', 'Ezequiel', 'Noel', 'Pablo', 'Cade', 'Pedro', 'Sullivan', 'Trevor', 'Reed', 'Quinn', 'Frank', 'Harvey', 'Princeton', 'Zayne', 'Matthias', 'Conor', 'Sterling', 'Dax', 'Grady', 'Cyrus', 'Gage', 'Leland', 'Solomon', 'Emanuel', 'Niko', 'Ruben', 'Kasen', 'Mathias', 'Kashton', 'Franklin', 'Remy', 'Shane', 'Kendrick', 'Shawn', 'Otto', 'Armani', 'Keegan', 'Finnegan', 'Memphis', 'Bowen', 'Dominick', 'Kolton', 'Jamison', 'Allen', 'Philip', 'Tate', 'Peyton', 'Jase', 'Oakley', 'Rhys', 'Kyson', 'Adan', 'Esteban', 'Dalton', 'Gianni', 'Callum', 'Sage', 'Alexis', 'Milan', 'Moises', 'Jonas', 'Uriel', 'Colson', 'Marcos', 'Zaiden', 'Hank', 'Damon', 'Hugo', 'Ronin', 'Royal', 'Kamden', 'Dexter', 'Luciano', 'Alonzo', 'Augustus', 'Kamari', 'Eden', 'Roberto', 'Baker', 'Bruce', 'Kian', 'Albert', 'Frederick', 'Mohamed', 'Abram', 'Omari', 'Porter', 'Enrique', 'Alijah', 'Francis', 'Leonidas', 'Zachariah', 'Landen', 'Wilder', 'Apollo', 'Santino', 'Tatum', 'Pierce', 'Forrest', 'Corey', 'Derrick', 'Isaias', 'Kaison', 'Kieran', 'Arjun', 'Gunnar', 'Rocco', 'Emmitt', 'Abdiel', 'Braylen', 'Maximilian', 'Skyler', 'Phillip', 'Benson', 'Cannon', 'Deacon', 'Dorian', 'Asa', 'Moses', 'Ayaan', 'Jayson', 'Raul', 'Briggs', 'Armando', 'Nikolai', 'Cassius', 'Drew', 'Rodrigo', 'Raphael', 'Danny', 'Conrad', 'Moshe', 'Zyaire', 'Julio', 'Casey', 'Ronald', 'Scott', 'Callan', 'Roland', 'Saul', 'Jalen', 'Brycen', 'Ryland', 'Lawrence', 'Davis', 'Rowen', 'Zain', 'Ermias', 'Jaime', 'Duke', 'Stetson', 'Alec', 'Yusuf', 'Case', 'Trenton', 'Callen', 'Ariel', 'Jasiah', 'Soren', 'Dennis', 'Donald', 'Keith', 'Izaiah', 'Lewis', 'Kylan', 'Kobe', 'Makai', 'Rayan', 'Ford', 'Zaire', 'Landyn', 'Roy', 'Bo', 'Chris', 'Jamari', 'Ares', 'Mohammad', 'Darius', 'Drake', 'Tripp', 'Marcelo', 'Samson', 'Dustin', 'Layton', 'Gerardo', 'Johan', 'Kaysen', 'Keaton', 'Reece', 'Chandler', 'Lucca', 'Mack', 'Baylor', 'Kannon', 'Marvin', 'Huxley', 'Nixon', 'Tony', 'Cason', 'Mauricio', 'Quentin', 'Edison', 'Quincy', 'Ahmed', 'Finnley', 'Justice', 'Taylor', 'Gustavo', 'Brock', 'Ahmad', 'Kyree', 'Arturo', 'Nikolas', 'Boston', 'Sincere', 'Alessandro', 'Braylon', 'Colby', 'Leonard', 'Ridge', 'Trey', 'Aden', 'Leandro', 'Sam', 'Uriah', 'Ty', 'Sylas', 'Axton', 'Issac', 'Fletcher', 'Julien', 'Wells', 'Alden', 'Vihaan', 'Jamir', 'Valentino', 'Shepherd', 'Keanu', 'Hezekiah', 'Lionel', 'Kohen', 'Zaid', 'Alberto', 'Neil', 'Denver', 'Aarav', 'Brendan', 'Dillon', 'Koda', 'Sutton', 'Kingsley', 'Sonny', 'Alfredo', 'Wilson', 'Harry', 'Jaziel', 'Salvador', 'Cullen', 'Hamza', 'Dariel', 'Rex', 'Zeke', 'Mohammed', 'Nelson', 'Boone', 'Ricky', 'Santana', 'Cayson', 'Lance', 'Raylan', 'Lucian', 'Eliel', 'Alvin', 'Jagger', 'Braden', 'Curtis', 'Mathew', 'Jimmy', 'Kareem', 'Archie', 'Amos', 'Quinton', 'Yosef', 'Bodie', 'Jerry', 'Langston', 'Axl', 'Stanley', 'Clay', 'Douglas', 'Layne', 'Titan', 'Tomas', 'Houston', 'Darren', 'Lachlan', 'Kase', 'Korbin', 'Leighton', 'Joziah', 'Samir', 'Watson', 'Colten', 'Roger', 'Shiloh', 'Tommy', 'Mitchell', 'Azariah', 'Noe', 'Talon', 'Deandre', 'Lochlan', 'Joe', 'Carmelo', 'Otis', 'Randy', 'Byron', 'Chaim', 'Lennon', 'Devon', 'Nathanael', 'Bruno', 'Aryan', 'Flynn', 'Vicente', 'Brixton', 'Kyro', 'Brennan', 'Casen', 'Kenzo', 'Orlando', 'Castiel', 'Rayden', 'Ben', 'Grey', 'Jedidiah', 'Tadeo', 'Morgan', 'Augustine', 'Mekhi', 'Abdullah', 'Ramon', 'Saint', 'Emery', 'Maurice', 'Jefferson', 'Maximo', 'Koa', 'Ray', 'Jamie', 'Eddie', 'Guillermo', 'Onyx', 'Thaddeus', 'Wayne', 'Hassan', 'Alonso', 'Dash', 'Elisha', 'Jaxxon', 'Rohan', 'Carl', 'Kelvin', 'Jon', 'Larry', 'Reese', 'Aldo', 'Marcel', 'Melvin', 'Yousef', 'Aron', 'Kace', 'Vincenzo', 'Kellan', 'Miller', 'Jakob', 'Reign', 'Kellen', 'Kristopher', 'Ernesto', 'Briar', 'Gary', 'Trace', 'Joey', 'Clyde', 'Enoch', 'Jaxx', 'Crosby', 'Magnus', 'Fisher', 'Jadiel', 'Bronson', 'Eugene', 'Lee', 'Brecken', 'Atreus', 'Madden', 'Khari', 'Caspian', 'Ishaan', 'Kristian', 'Westley', 'Hugh', 'Kamryn', 'Musa', 'Rey', 'Thatcher', 'Alfred', 'Emory', 'Kye', 'Reyansh', 'Yahir', 'Cain', 'Mordechai', 'Zayd', 'Demetrius', 'Harley', 'Felipe', 'Louie', 'Branson', 'Graysen', 'Allan', 'Kole', 'Harold', 'Alvaro', 'Harlan', 'Amias', 'Brett', 'Khalid', 'Misael', 'Westin', 'Zechariah', 'Aydin', 'Kaiser', 'Lian', 'Bryant', 'Junior', 'Legacy', 'Ulises', 'Bellamy', 'Brayan', 'Kody', 'Ledger', 'Eliseo', 'Gordon', 'London', 'Rocky', 'Valentin', 'Terry', 'Damari', 'Trent', 'Bentlee', 'Canaan', 'Gatlin', 'Kiaan', 'Franco', 'Eithan', 'Idris', 'Krew', 'Yehuda', 'Marlon', 'Rodney', 'Creed', 'Salvatore', 'Stefan', 'Tristen', 'Adrien', 'Jamal', 'Judson', 'Camilo', 'Kenny', 'Nova', 'Robin', 'Rudy', 'Van', 'Bjorn', 'Brodie', 'Mac', 'Jacoby', 'Sekani', 'Vivaan', 'Blaine', 'Ira', 'Ameer', 'Dominik', 'Alaric', 'Dane', 'Jeremias', 'Kyng', 'Reginald', 'Bobby', 'Kabir', 'Jairo', 'Alexzander', 'Benicio', 'Vance', 'Wallace', 'Zavier', 'Billy', 'Callahan', 'Dakari', 'Gerald', 'Turner', 'Bear', 'Jabari', 'Cory', 'Fox', 'Harlem', 'Jakari', 'Jeffery', 'Maxton', 'Ronnie', 'Yisroel', 'Zakai', 'Bridger', 'Remi', 'Arian', 'Blaze', 'Forest', 'Genesis', 'Jerome', 'Reuben', 'Wesson', 'Anders', 'Banks', 'Calum', 'Dayton', 'Kylen', 'Dangelo', 'Emir', 'Malakhi', 'Salem', 'Blaise', 'Tru', 'Boden', 'Kolten', 'Kylo', 'Aries', 'Henrik', 'Kalel', 'Landry', 'Marcellus', 'Zahir', 'Lyle', 'Dario', 'Rene', 'Terrance', 'Xzavier', 'Alfonso', 'Darian', 'Kylian', 'Maison', 'Foster', 'Keenan', 'Yahya', 'Heath', 'Javion', 'Jericho', 'Aziel', 'Darwin', 'Marquis', 'Mylo', 'Ambrose', 'Anakin', 'Jordy', 'Juelz', 'Toby', 'Yael', 'Azrael', 'Brentley', 'Tristian', 'Bode', 'Jovanni', 'Santos', 'Alistair', 'Braydon', 'Kamdyn', 'Marc', 'Mayson', 'Niklaus', 'Simeon', 'Colter', 'Davion', 'Leroy', 'Ayan', 'Dilan', 'Ephraim', 'Anson', 'Merrick', 'Wes', 'Will', 'Jaxen', 'Maxim', 'Howard', 'Jad', 'Jesiah', 'Ignacio', 'Zyon', 'Ahmir', 'Jair', 'Mustafa', 'Jermaine', 'Yadiel', 'Aayan', 'Dhruv', 'Seven']

    
female_names = ['Olivia', 'Emma', 'Ava', 'Sophia', 'Isabella', 'Charlotte', 'Amelia', 'Mia', 'Harper', 'Evelyn', 'Abigail', 'Emily', 'Ella', 'Elizabeth', 'Camila', 'Luna', 'Sofia', 'Avery', 'Mila', 'Aria', 'Scarlett', 'Penelope', 'Layla', 'Chloe', 'Victoria', 'Madison', 'Eleanor', 'Grace', 'Nora', 'Riley', 'Zoey', 'Hannah', 'Hazel', 'Lily', 'Ellie', 'Violet', 'Lillian', 'Zoe', 'Stella', 'Aurora', 'Natalie', 'Emilia', 'Everly', 'Leah', 'Aubrey', 'Willow', 'Addison', 'Lucy', 'Audrey', 'Bella', 'Nova', 'Brooklyn', 'Paisley', 'Savannah', 'Claire', 'Skylar', 'Isla', 'Genesis', 'Naomi', 'Elena', 'Caroline', 'Eliana', 'Anna', 'Maya', 'Valentina', 'Ruby', 'Kennedy', 'Ivy', 'Ariana', 'Aaliyah', 'Cora', 'Madelyn', 'Alice', 'Kinsley', 'Hailey', 'Gabriella', 'Allison', 'Gianna', 'Serenity', 'Samantha', 'Sarah', 'Autumn', 'Quinn', 'Eva', 'Piper', 'Sophie', 'Sadie', 'Delilah', 'Josephine', 'Nevaeh', 'Adeline', 'Arya', 'Emery', 'Lydia', 'Clara', 'Vivian', 'Madeline', 'Peyton', 'Julia', 'Rylee', 'Brielle', 'Reagan', 'Natalia', 'Jade', 'Athena', 'Maria', 'Leilani', 'Everleigh', 'Liliana', 'Melanie', 'Mackenzie', 'Hadley', 'Raelynn', 'Kaylee', 'Rose', 'Arianna', 'Isabelle', 'Melody', 'Eliza', 'Lyla', 'Katherine', 'Aubree', 'Adalynn', 'Kylie', 'Faith', 'Mary', 'Margaret', 'Ximena', 'Iris', 'Alexandra', 'Jasmine', 'Charlie', 'Amaya', 'Taylor', 'Isabel', 'Ashley', 'Khloe', 'Ryleigh', 'Alexa', 'Amara', 'Valeria', 'Andrea', 'Parker', 'Norah', 'Eden', 'Elliana', 'Brianna', 'Emersyn', 'Valerie', 'Anastasia', 'Eloise', 'Emerson', 'Cecilia', 'Remi', 'Josie', 'Alina', 'Reese', 'Bailey', 'Lucia', 'Adalyn', 'Molly', 'Ayla', 'Sara', 'Daisy', 'London', 'Jordyn', 'Esther', 'Genevieve', 'Harmony', 'Annabelle', 'Alyssa', 'Ariel', 'Aliyah', 'Londyn', 'Juliana', 'Morgan', 'Summer', 'Juliette', 'Trinity', 'Callie', 'Sienna', 'Blakely', 'Alaia', 'Kayla', 'Teagan', 'Alaina', 'Brynlee', 'Finley', 'Catalina', 'Sloane', 'Rachel', 'Lilly', 'Ember', 'Kimberly', 'Juniper', 'Sydney', 'Arabella', 'Gemma', 'Jocelyn', 'Freya', 'June', 'Lauren', 'Amy', 'Presley', 'Georgia', 'Journee', 'Elise', 'Rosalie', 'Ada', 'Laila', 'Brooke', 'Diana', 'Olive', 'River', 'Payton', 'Ariella', 'Daniela', 'Raegan', 'Alayna', 'Gracie', 'Mya', 'Blake', 'Noelle', 'Ana', 'Leila', 'Paige', 'Lila', 'Nicole', 'Rowan', 'Hope', 'Ruth', 'Alana', 'Selena', 'Marley', 'Kamila', 'Alexis', 'Mckenzie', 'Zara', 'Millie', 'Magnolia', 'Kali', 'Kehlani', 'Catherine', 'Maeve', 'Adelyn', 'Sawyer', 'Elsie', 'Lola', 'Jayla', 'Adriana', 'Journey', 'Vera', 'Aspen', 'Joanna', 'Alivia', 'Angela', 'Dakota', 'Camille', 'Nyla', 'Tessa', 'Brooklynn', 'Malia', 'Makayla', 'Rebecca', 'Fiona', 'Mariana', 'Lena', 'Julianna', 'Vanessa', 'Juliet', 'Camilla', 'Kendall', 'Harley', 'Cali', 'Evangeline', 'Mariah', 'Jane', 'Zuri', 'Elaina', 'Sage', 'Amira', 'Adaline', 'Lia', 'Charlee', 'Delaney', 'Lilah', 'Miriam', 'Angelina', 'Mckenna', 'Aniyah', 'Phoebe', 'Michelle', 'Thea', 'Hayden', 'Maggie', 'Lucille', 'Amiyah', 'Annie', 'Alexandria', 'Myla', 'Vivienne', 'Kiara', 'Alani', 'Margot', 'Adelaide', 'Briella', 'Brynn', 'Saylor', 'Destiny', 'Amari', 'Evelynn', 'Haven', 'Phoenix', 'Izabella', 'Kaia', 'Lilliana', 'Harlow', 'Alessandra', 'Madilyn', 'Nina', 'Logan', 'Adelynn', 'Amina', 'Kate', 'Fatima', 'Samara', 'Winter', 'Giselle', 'Evie', 'Arielle', 'Jessica', 'Talia', 'Leia', 'Gabriela', 'Gracelyn', 'Lexi', 'Laura', 'Makenzie', 'Melissa', 'Royalty', 'Rylie', 'Raelyn', 'Gabrielle', 'Paris', 'Daleyza', 'Joy', 'Maisie', 'Oakley', 'Ariyah', 'Kailani', 'Alayah', 'Stephanie', 'Amora', 'Willa', 'Gracelynn', 'Elle', 'Keira', 'Tatum', 'Veronica', 'Milani', 'Felicity', 'Paislee', 'Allie', 'Nylah', 'Ariah', 'Cassidy', 'Lyric', 'Madeleine', 'Miracle', 'Gwendolyn', 'Octavia', 'Dahlia', 'Heidi', 'Celeste', 'Remington', 'Makenna', 'Everlee', 'Scarlet', 'Esmeralda', 'Maci', 'Lainey', 'Jacqueline', 'Kira', 'Lana', 'Brinley', 'Demi', 'Ophelia', 'Lennon', 'Reign', 'Bristol', 'Sabrina', 'Alaya', 'Jennifer', 'Kenzie', 'Angel', 'Luciana', 'Anaya', 'Hallie', 'Ryan', 'Camryn', 'Kinley', 'Daniella', 'Lilith', 'Blair', 'Amanda', 'Collins', 'Jordan', 'Maliyah', 'Rosemary', 'Cataleya', 'Kaylani', 'Gia', 'Alison', 'Leighton', 'Nadia', 'Sutton', 'Carolina', 'Skye', 'Alicia', 'Regina', 'Viviana', 'Yaretzi', 'Heaven', 'Serena', 'Raven', 'Emely', 'Carmen', 'Wren', 'Helen', 'Charleigh', 'Danielle', 'Daphne', 'Esme', 'Nayeli', 'Maddison', 'Sarai', 'Dylan', 'Frances', 'Elisa', 'Mabel', 'Skyler', 'Jenna', 'Emelia', 'Kaitlyn', 'Miranda', 'Marlee', 'Matilda', 'Selah', 'Jolene', 'Wynter', 'Hattie', 'Bianca', 'Haley', 'Lorelei', 'Mira', 'Braelynn', 'Annalise', 'Madelynn', 'Katie', 'Palmer', 'Aylin', 'Elliott', 'Kyla', 'Rory', 'Avianna', 'Liana', 'Shiloh', 'Kalani', 'Jada', 'Kelsey', 'Elianna', 'Jimena', 'Kora', 'Kamryn', 'Ainsley', 'Averie', 'Kensley', 'Helena', 'Holly', 'Emory', 'Macie', 'Amber', 'Zariah', 'Erin', 'Eve', 'Kathryn', 'Renata', 'Kayleigh', 'Emmy', 'Celine', 'Francesca', 'Fernanda', 'April', 'Shelby', 'Poppy', 'Colette', 'Meadow', 'Nia', 'Sierra', 'Cheyenne', 'Edith', 'Oaklynn', 'Kennedi', 'Abby', 'Danna', 'Jazlyn', 'Alessia', 'Mikayla', 'Alondra', 'Addilyn', 'Leona', 'Mckinley', 'Carter', 'Maren', 'Sylvia', 'Alejandra', 'Ariya', 'Astrid', 'Adrianna', 'Charli', 'Imani', 'Maryam', 'Christina', 'Stevie', 'Maia', 'Adelina', 'Dream', 'Aisha', 'Alanna', 'Itzel', 'Azalea', 'Katelyn', 'Kylee', 'Leslie', 'Madilynn', 'Myra', 'Virginia', 'Remy', 'Hanna', 'Aleah', 'Jaliyah', 'Antonella', 'Aviana', 'Cameron', 'Chelsea', 'Cecelia', 'Alia', 'Mae', 'Cadence', 'Emberly', 'Charley', 'Janelle', 'Mallory', 'Kaliyah', 'Elaine', 'Gloria', 'Jayleen', 'Lorelai', 'Malaysia', 'Bethany', 'Briana', 'Beatrice', 'Dorothy', 'Rosie', 'Jemma', 'Noa', 'Carly', 'Mariam', 'Anne', 'Karina', 'Emmalyn', 'Ivory', 'Ivanna', 'Jamie', 'Kara', 'Aitana', 'Jayda', 'Justice', 'Meredith', 'Briar', 'Skyla', 'Khaleesi', 'Dayana', 'Julieta', 'Katalina', 'Kendra', 'Oaklyn', 'Ashlyn', 'Armani', 'Jazmin', 'Kyra', 'Angelica', 'Zahra', 'Dallas', 'Johanna', 'Elliot', 'Macy', 'Monroe', 'Kimber', 'Henley', 'Ari', 'Karsyn', 'Lyanna', 'Lilian', 'Amalia', 'Nola', 'Dior', 'Aleena', 'Megan', 'Michaela', 'Amirah', 'Cassandra', 'Melany', 'Legacy', 'Reyna', 'Alma', 'Emmie', 'Melina', 'Siena', 'Priscilla', 'Ashlynn', 'Savanna', 'Sloan', 'Tiana', 'Aubrie', 'Coraline', 'Reina', 'Allyson', 'Kaydence', 'Sasha', 'Julie', 'Alexia', 'Irene', 'Marilyn', 'Greta', 'Braelyn', 'Emerie', 'Lylah', 'Nalani', 'Monica', 'Aileen', 'Lauryn', 'Anahi', 'Aurelia', 'Kassidy', 'Rayna', 'Romina', 'Lillie', 'Marie', 'Rosa', 'Saige', 'Bonnie', 'Kelly', 'Xiomara', 'Annabella', 'Avah', 'Lacey', 'Anya', 'Liberty', 'Karen', 'Mercy', 'Zelda', 'Baylee', 'Chaya', 'Kenna', 'Roselyn', 'Liv', 'Mara', 'Ensley', 'Malani', 'Malaya', 'Hadassah', 'Lyra', 'Adley', 'Galilea', 'Jaylah', 'Karla', 'Nala', 'Opal', 'Aliza', 'Milena', 'Ailani', 'Louisa', 'Mina', 'Kairi', 'Clementine', 'Louise', 'Maleah', 'Janiyah', 'Marina', 'Anika', 'Julissa', 'Bailee', 'Hayley', 'Jessie', 'Laney', 'Eileen', 'Faye', 'Kynlee', 'Tiffany', 'Lara', 'Angie', 'Joelle', 'Rhea', 'Calliope', 'Jazmine', 'Amani', 'Haylee', 'Aliana', 'Leyla', 'Jolie', 'Kinslee', 'Ryann', 'Simone', 'Milan', 'Lennox', 'Treasure', 'Alora', 'Ellis', 'Rebekah', 'Mikaela', 'Lina', 'Harmoni', 'Yareli', 'Giuliana', 'Lea', 'Harlee', 'Elyse', 'Frida', 'Blaire', 'Aya', 'Laurel', 'Meghan', 'Pearl', 'Zaylee', 'Alena', 'Holland', 'Bria', 'Rayne', 'Bridget', 'Zariyah', 'Kori', 'Frankie', 'Clarissa', 'Brylee', 'Davina', 'Rivka', 'Cynthia', 'Zaria', 'Madalyn', 'Paula', 'Salem', 'Amelie', 'Madisyn', 'Vienna', 'Haisley', 'Ainhoa', 'Journi', 'Karter', 'Oaklee', 'Livia', 'Miley', 'Adele', 'Amaia', 'Yara', 'Averi', 'Emmeline', 'Kyleigh', 'Princess', 'Penny', 'Sariyah', 'Amayah', 'Crystal', 'Keyla', 'Lilyana', 'Linda', 'Aniya', 'Marianna', 'Alaiya', 'Noemi', 'Chanel', 'Estella', 'Isabela', 'Jillian', 'Kallie', 'Ellianna', 'Elsa', 'Itzayana', 'Zora', 'Estelle', 'Chana', 'Raina', 'Royal', 'Sunny', 'Estrella', 'Martha', 'Ellen', 'Kailey', 'Maxine', 'Clare', 'Teresa', 'Annika', 'Kamilah', 'Azariah', 'Della', 'Addyson', 'Kai', 'Lilianna', 'Tinsley', 'Yaritza', 'Navy', 'Winnie', 'Andi', 'Kamiyah', 'Waverly', 'Sky', 'Amaris', 'Ramona', 'Saoirse', 'Hana', 'Judith', 'Halle', 'Laylah', 'Novalee', 'Jaycee', 'Zaniyah', 'Alianna', 'Paulina', 'Jayde', 'Thalia', 'Giovanna', 'Gwen', 'Iliana', 'Elora', 'Ezra', 'Kaylie', 'Braylee', 'Mavis', 'Ellison', 'Margo', 'Mylah', 'Paisleigh', 'Analia', 'August', 'Brittany', 'Kaisley', 'Belen', 'Promise', 'Amiya', 'Dalary', 'Veda', 'Alisson', 'Keilani', 'Oakleigh', 'Guadalupe', 'Leanna', 'Rosalyn', 'Selene', 'Theodora', 'Kamari', 'Anais', 'Elodie', 'Celia', 'Dani', 'Hunter', 'Indie', 'Kenia', 'Nellie', 'Belle', 'Kataleya', 'Lexie', 'Miah', 'Rylan', 'Sylvie', 'Valery', 'Addilynn', 'Dulce', 'Marissa', 'Meilani', 'Natasha', 'Jaylee', 'Kimora', 'Raquel', 'Scarlette', 'Aliya', 'Nataly', 'Whitney', 'Corinne', 'Denver', 'Nathalie', 'Kiera', 'Milana', 'Vada', 'Violeta', 'Luz', 'Addisyn', 'Casey', 'Deborah', 'Tori', 'Zainab', 'Erika', 'Jenesis', 'Avalynn', 'Nancy', 'Emmalynn', 'Hadlee', 'Heavenly', 'Aubrielle', 'Elisabeth', 'Salma', 'Adalee', 'Landry', 'Malayah', 'Novah', 'Egypt', 'Ayleen', 'Blessing', 'Elina', 'Joyce', 'Myah', 'Zoie', 'Christine', 'Jaelynn', 'Persephone', 'Chandler', 'Emmaline', 'Paloma', 'Harleigh', 'Noor', 'Paola', 'India', 'Madalynn', 'Rosalee', 'Florence', 'Maliah', 'Flora', 'Luella', 'Patricia', 'Whitley', 'Carolyn', 'Kathleen', 'Keily', 'Kiana', 'Tenley', 'Alyson', 'Barbara', 'Dana', 'Yasmin', 'Bexley', 'Micah', 'Tatiana', 'Arden', 'Aubriella', 'Lindsey', 'Emani', 'Hailee', 'Lisa', 'Sevyn', 'Fallon', 'Magdalena', 'Tinley', 'Halo', 'Lailah', 'Arlette', 'Ansley', 'Esperanza', 'Cleo', 'Aila', 'Emerald', 'Jaelyn', 'Karlee', 'Kaya', 'Ingrid', 'Jewel', 'Emilee', 'Giana', 'Paityn', 'Zola', 'Amoura', 'Renee', 'Ann', 'Berkley', 'Harriet', 'Queen', 'Sariah', 'Beatrix', 'Sandra', 'Alannah', 'Austyn', 'Freyja', 'Kaylin', 'Samira', 'Taliyah', 'Hadleigh', 'Kaiya', 'Robin', 'Luisa', 'Zendaya', 'Ariadne', 'Dixie']

names = male_names + female_names

colors = [
    "Red","Orange","Yellow","Green","Blue","Purple",
    "Tan","Turquoise","Silver","Pink","Gray",
]

emotion_adj = [    
    "Accepting","Accommodating","Afraid","Aggressive","Agitated","Alarmed","Amazed",
    "Amused","Antagonistic","Anxious","Apathetic","Apprehensive","Arrogant","Bothered","Brave","Calm","Charming",
    "Cheerful","Competitive","Confident","Conscientious","Conservative","Creative","Curious",
    "Cynical","Distracted","Distraught","Distressed","Downcast",
    "Earnest","Gloomy","Grouchy","Guilty","Heroic","Hopeful",
    "Hostile","Humble","Jovial","Joyful","Jumpy","Mysterious","Opinionated",
    "Panicky","Passionate","Patient","Quarrelsome","Rational","Reasonable",
    "Sad","Safe","Scared","Scornful","Selfish",
    "Thoughtful","Tolerant","Tranquil","Treacherous","Welcoming","Witty","Zealous","Zany",
    "Supportive","Sardonic","Secretive","Bitter",
]

roles = [
    "actor","artist","butler","crook","director",
    "expert","fisherman","judge","juror","painter","musician",
    "policeman","fireman","professor","sheriff","soldier","student",
    "philosopher","teacher","tourist","lawyer","physician","engineer",
    "veterinarian","dentist","accountant","technician","electrician",
    "psychologist","physicist","plumber","waiter","mechanic","cook",
    "librarian","hairdresser","economist","bartender","cashier","surgeon",
    "pilot","butcher","optician","athlete","cleaner",
    "actuary","sailor","therapist","secret_agent","animal_breeder","air_traffic_controller",
    "athropologist","animal_trainer","allergist","real_estate_agent","archeologist",
    "astronomer","athletic_trainer","audiologist","auditor","bailiff",
    "baker","barber","clerk","cartographer","chiropractor","dancer","epidemiologist",
    "farmer","floral_designer","forester","truck_driver","jeweler","interior_designer",
    "machinist","mathematician","secretary","photographer","radio_announcer","roofer",
    "paver","taxi_driver","historian","poet","stunt_performer","monologist","publisher",
    "scribe","blogger","copy_editor","ceo","ticket_controller","station_master","surveyor",
    "driller", "scholar", "quant", "cfo" , "cto", "cio", "computer_scientist", "prisoner", 
    "guest", "visitor", "helper", "breadwinner", "host", "ghost", "playmaker", "scorer", 
    "settler", "reacher", "cynic", "witch", "captain", "buisness_analyst", "data_scientist",
    "trader", "principal", "ballerina", "footballer", "cricketer", "tennis_player", "lecturer", 
    "patient", "ai_scientist", "philosopher", "cyclist", "chess_player", "stratergist", 
    "scientist", "parent", "fbi_agent", "defender" , "attacker", "warlord", "nlp_engineer", 
    "grandmaster", "master", "king", "queen", "knight", "prince", "princess", "baby", "adult",
    "advisor", "wrestler", "fighter", "boxer", "bee_keeper", "musian", "dj_artist", "violinist",
    "conductor", "gymnast"
]

count_furniture = [
    "chair","table","desk","stool","couch","bookcase",
    "bed","mattress","dresser","futon","nightstand","storage_container",
    "hammock","billiard_table","piano","chess_board","door",
]


count_animals = [
    "aardvark","dog","alpaca","armadillo","anteater","penguin",
    "ant","bear","bonobo","beaver","bird","owl","butterfly",
    "buffalo","bumblebee","frog","whale","bison","badger","baboon",
    "rhinoceros","camel","cat","chicken","cheetah","cockatoo","cow","crab",
    "catepillar","chimpanzee","loon","spider","crocodile","coyote","chincilla",
    "duck","deer","dolphin","dingo","donkey","eel","elephant","emu","gorilla","falcon",
    "fox","ferret","gerbil","grasshopper","gopher","goat","hyena","horse","hippopotamus",
    "jaguar","kangaroo","lemur","lion","lynx","lizard","marmot","mink","muskrat","mouse",
    "macaw","moose","newt","ostrich","otter","pig","puffin","puma","pelican","peacock",
    "rabbit","snake","reindeer","raccoon","rat","sheep","vulture","wombat","wolf","warthog",
    "walrus","weasel","boar","zebra","seal",
]

verbs = ["like", "admire", "pet", "make", "break", "hit", "eat", "kill", "fight", "steal", "touch",
         "approve", "defend", "replace", "chase", "hunt", "dislike", "recognize", "understand", "feel",
         "love", "hate", "impress", "know", "notice", "perceive", "see", "remember", "surprise", "prefer",
         "draw", "accuse", "adore", "advise", "appreciate", "approach", "astonish", "need", "call", "believe",
         "follow", "serve", "consult", "convince", "criticize", "desire", "doubt", "encourage", "examine",
         "feed", "forgive", "hug", "investigate", "kiss", "mention", "owe", "persuade", "propose", "promise",
         "punch", "shoot", "threaten", "tolerate", "warn"]

In [ ]:
len(male_names), len(female_names), len(roles), len(verbs), len(emotion_adj)

(997, 1000, 156, 64, 65)

In [ ]:
from nltk import *
from nltk.sem.drt import DrtParser
from nltk.sem import logic
import nltk
from nltk.sem import Expression
from nltk import load_parser
from nltk.sem import Valuation, Model
from nltk.corpus import brown


import random
import re

import numpy as np
import pandas as pd

from nltk.parse.generate import generate

import inflect

plural = inflect.engine()

In [ ]:
import random

def template_anaphora(template_name):
  templates = {
      "2q_n_v_n_v_si_si": "{} {} {} {} {} who {} {}",
      "2q_n_v_n_v_si_pl": "{} {} {} {} {} who {} {}",
      "2q_n_v_n_v_pl_si": "{} {} {} {} {} who {} {}",
      "2q_n_v_n_v_pl_pl": "{} {} {} {} {} who {} {}",
      "2q_n_v_n_v_neg_si_si": "{} {} {} {} {} who does not {} {}",
      "2q_n_v_n_v_neg_si_pl": "{} {} {} {} {} who do not {} {}",
      "2q_n_v_n_v_neg_pl_si": "{} {} {} {} {} who does not {} {}",
      "2q_n_v_n_v_neg_pl_pl": "{} {} {} {} {} who do not {} {}",
      "2q_n_v_neg_n_v_si_si": "{} {} does not {} {} {} who {} {}",
      "2q_n_v_neg_n_v_pl_si": "{} {} do not {} {} {} who {} {}",
      "2q_n_v_neg_n_v_si_pl": "{} {} does not {} {} {} who {} {}",
      "2q_n_v_neg_n_v_pl_pl": "{} {} do not {} {} {} who {} {}",
      "2q_n_v_neg_n_v_neg_si_si": "{} {} does not {} {} {} who does not {} {}",
      "2q_n_v_neg_n_v_neg_si_pl": "{} {} does not {} {} {} who do not {} {}",
      "2q_n_v_neg_n_v_neg_pl_si": "{} {} do not {} {} {} who does not {} {}",
      "2q_n_v_neg_n_v_neg_pl_pl": "{} {} do not {} {} {} who do not {} {}",
      "2q_n_v_n_neg_v_si_si": "{} {} {} {} non-{} who {} {}",
      "2q_n_v_n_neg_v_si_pl": "{} {} {} {} non-{} who {} {}",
      "2q_n_v_n_neg_v_pl_si": "{} {} {} {} non-{} who {} {}",
      "2q_n_v_n_neg_v_pl_pl": "{} {} {} {} non-{} who {} {}",
      "2q_n_v_n_neg_v_neg_si_si": "{} {} {} {} non-{} who does not {} {}",
      "2q_n_v_n_neg_v_neg_si_pl": "{} {} {} {} non-{} who do not {} {}",
      "2q_n_v_n_neg_v_neg_pl_si": "{} {} {} {} non-{} who does not {} {}",
      "2q_n_v_n_neg_v_neg_pl_pl": "{} {} {} {} non-{} who do not {} {}",
      "2q_n_v_neg_n_neg_v_si_si": "{} {} does not {} {} non-{} who {} {}",
      "2q_n_v_neg_n_neg_v_pl_si": "{} {} do not {} {} non-{} who {} {}",
      "2q_n_v_neg_n_neg_v_si_pl": "{} {} does not {} {} non-{} who {} {}",
      "2q_n_v_neg_n_neg_v_pl_pl": "{} {} do not {} {} non-{} who {} {}",
      "2q_n_v_neg_n_neg_v_neg_si_si": "{} {} does not {} {} non-{} who does not {} {}",
      "2q_n_v_neg_n_neg_v_neg_si_pl": "{} {} does not {} {} non-{} who do not {} {}",
      "2q_n_v_neg_n_neg_v_neg_pl_si": "{} {} do not {} {} non-{} who does not {} {}",
      "2q_n_v_neg_n_neg_v_neg_pl_pl": "{} {} do not {} {} non-{} who do not {} {}",
      "2q_n_neg_v_n_v_si_si": "{} non-{} {} {} {} who {} {}",
      "2q_n_neg_v_n_v_si_pl": "{} non-{} {} {} {} who {} {}",
      "2q_n_neg_v_n_v_pl_si": "{} non-{} {} {} {} who {} {}",
      "2q_n_neg_v_n_v_pl_pl": "{} non-{} {} {} {} who {} {}",
      "2q_n_neg_v_n_v_neg_si_si": "{} non-{} {} {} {} who does not {} {}",
      "2q_n_neg_v_n_v_neg_si_pl": "{} non-{} {} {} {} who do not {} {}",
      "2q_n_neg_v_n_v_neg_pl_si": "{} non-{} {} {} {} who does not {} {}",
      "2q_n_neg_v_n_v_neg_pl_pl": "{} non-{} {} {} {} who do not {} {}",
      "2q_n_neg_v_neg_n_v_si_si": "{} non-{} does not {} {} {} who {} {}",
      "2q_n_neg_v_neg_n_v_si_pl": "{} non-{} does not {} {} {} who {} {}",
      "2q_n_neg_v_neg_n_v_pl_si": "{} non-{} do not {} {} {} who {} {}",
      "2q_n_neg_v_neg_n_v_pl_pl": "{} non-{} do not {} {} {} who {} {}",
      "2q_n_neg_v_neg_n_v_neg_si_si": "{} non-{} does not {} {} {} who does not {} {}",
      "2q_n_neg_v_neg_n_v_neg_si_pl": "{} non-{} does not {} {} {} who do not {} {}",
      "2q_n_neg_v_neg_n_v_neg_pl_si": "{} non-{} do not {} {} {} who does not {} {}",
      "2q_n_neg_v_neg_n_v_neg_pl_pl": "{} non-{} do not {} {} {} who do not {} {}",
      "2q_n_neg_v_n_neg_v_si_si": "{} non-{} {} {} non-{} who {} {}",
      "2q_n_neg_v_n_neg_v_si_pl": "{} non-{} {} {} non-{} who {} {}",
      "2q_n_neg_v_n_neg_v_pl_si": "{} non-{} {} {} non-{} who {} {}",
      "2q_n_neg_v_n_neg_v_pl_pl": "{} non-{} {} {} non-{} who {} {}",
      "2q_n_neg_v_n_neg_v_neg_si_si": "{} non-{} {} {} non-{} who does not {} {}",
      "2q_n_neg_v_n_neg_v_neg_si_pl": "{} non-{} {} {} non-{} who do not {} {}",
      "2q_n_neg_v_n_neg_v_neg_pl_si": "{} non-{} {} {} non-{} who does not {} {}",
      "2q_n_neg_v_n_neg_v_neg_pl_pl": "{} non-{} {} {} non-{} who do not {} {}",
      "2q_n_neg_v_neg_n_neg_v_si_si": "{} non-{} does not {} {} non-{} who {} {}",
      "2q_n_neg_v_neg_n_neg_v_si_pl": "{} non-{} does not {} {} non-{} who {} {}",
      "2q_n_neg_v_neg_n_neg_v_pl_si": "{} non-{} do not {} {} non-{} who {} {}",
      "2q_n_neg_v_neg_n_neg_v_pl_pl": "{} non-{} do not {} {} non-{} who {} {}",
      "2q_n_neg_v_neg_n_neg_v_neg_si_si": "{} non-{} does not {} {} non-{} who does not {} {}",
      "2q_n_neg_v_neg_n_neg_v_neg_si_pl": "{} non-{} does not {} {} non-{} who do not {} {}",
      "2q_n_neg_v_neg_n_neg_v_neg_pl_si": "{} non-{} do not {} {} non-{} who does not {} {}",
      "2q_n_neg_v_neg_n_neg_v_neg_pl_pl": "{} non-{} do not {} {} non-{} who do not {} {}",
      "propn_v_n_v_si": "{} {} {} {} who {} {}",
      "propn_v_n_v_pl": "{} {} {} {} who {} {}",
      "propn_v_n_v_neg_si": "{} {} {} {} who does not {} {}",
      "propn_v_n_v_neg_pl": "{} {} {} {} who do not {} {}",
      "propn_v_neg_n_v_si": "{} does not {} {} {} who {} {}",
      "propn_v_neg_n_v_pl": "{} does not {} {} {} who {} {}",
      "propn_v_neg_n_v_neg_si": "{} does not {} {} {} who does not {} {}",
      "propn_v_neg_n_v_neg_pl": "{} does not {} {} {} who do not {} {}",
      "propn_v_n_neg_v_si": "{} {} {} non-{} who {} {}",
      "propn_v_n_neg_v_pl": "{} {} {} non-{} who {} {}",
      "propn_v_n_neg_v_neg_si": "{} {} {} non-{} who does not {} {}",
      "propn_v_n_neg_v_neg_pl": "{} {} {} non-{} who do not {} {}",
      "propn_v_neg_n_neg_v_si": "{} does not {} {} non-{} who {} {}",
      "propn_v_neg_n_neg_v_pl": "{} does not {} {} non-{} who {} {}",
      "propn_v_neg_n_neg_v_neg_si": "{} does not {} {} non-{} who does not {} {}",
      "propn_v_neg_n_neg_v_neg_pl": "{} does not {} {} non-{} who do not {} {}",
  }

  return templates[template_name]


def select_det(quantifier):
  det = None
  if quantifier == "all":
    det = random.choice(["all", "every"])
  elif quantifier == "exists":
    det = random.choice(["some", "a"])
  return det

def natural_language_sentence_generation(quantifiers, variables, verb_functions, negations, type, male_name = False):
  dets = None

  if type == "2_quantifiers":
    dets = [select_det(quantifiers[0]), select_det(quantifiers[1])]
    template_id = "2q_n_"
    if negations[variables[0]] == True:
      template_id += "neg_"
    template_id += "v_"
    if negations[verb_functions[1]] == True:
      if quantifiers[0] == "all":
        dets[0] = "no"
        if quantifiers[1] == "all":
          dets[1] = "any"
        else :
          dets[1] = "every"
      elif (quantifiers[0] == "exists") and (quantifiers[1] == "exists"):
        dets[1] = "no"
      else :
        template_id += "neg_"
    template_id += "n_"
    if negations[variables[1]] == True:
      template_id += "neg_"
    template_id += "v_"
    if negations[verb_functions[0]] == True:
      template_id += "neg_"
    
    if dets[0] in ["all", "some"]:
      template_id += "pl_"
      pronoun = "them"
    else :
      template_id += "si_"
      pronoun = random.choice(["him", "her"])
    
    if dets[1] in ["all", "some"]:
      template_id += "pl"
    else :
      template_id += "si"

    return template_anaphora(template_id).format(dets[0], variables[0], verb_functions[1], dets[1], variables[1], verb_functions[0], pronoun)

  else :
    dets = [select_det(quantifiers[0])]
    template_id = "propn_v_"
    if negations[verb_functions[1]] == True :
      if quantifiers[0] == "exists":
        dets[0] = "no"
      else :
        template_id += "neg_"
    template_id += "n_"
    if negations[variables[1]] == True :
      template_id += "neg_"
    template_id += "v_"
    if negations[verb_functions[0]] == True :
      template_id += "neg_"

    template_id += "pl" if dets[0] in ["all", "some"] else "si"

    pronoun = "him" if male_name else "her"

    return template_anaphora(template_id).format(variables[0], verb_functions[1], dets[0], variables[1], verb_functions[0], pronoun)



def anaphora_generate_logic_str(quantifiers, variables, verb_functions, negations, type):
  
  variables = ["-"+x if negations[x] else x for x in variables]
  verb_functions = ["-"+x if negations[x] else x for x in verb_functions]
  

  if type == "2_quantifiers":
    if quantifiers == ["all", "all"]:
      return "all x.({}(x) -> all y.({}(y) & {}(y,x) -> {}(x,y)))".format(variables[0], variables[1], verb_functions[0], verb_functions[1])
    elif quantifiers == ["all", "exists"]:
      return "all x.({}(x) -> exists y.({}(y) & {}(y,x) & {}(x,y)))".format(variables[0], variables[1], verb_functions[0], verb_functions[1])
    elif quantifiers == ["exists", "all"]:
      return "exists x.({}(x) & all y.({}(y) & {}(y,x) -> {}(x,y)))".format(variables[0], variables[1], verb_functions[0], verb_functions[1])
    elif quantifiers == ["exists", "exists"]:
      return "exists x.({}(x) & exists y.({}(y) & {}(y,x) & {}(x,y)))".format(variables[0], variables[1], verb_functions[0], verb_functions[1])
  else :
    if quantifiers == ["all"]:
      return "all x.({}(x) & {}(x, {}) -> {}({}, x))".format(variables[1], verb_functions[0] ,variables[0], verb_functions[1], variables[0])
    else :
      return "exists x.({}(x) & {}(x, {}) & {}({}, x))".format(variables[1], verb_functions[0] ,variables[0], verb_functions[1], variables[0])


def generate_sentence_anaphora(nouns, domain, verbs, prob = 0.85):

  verb_functions = random.sample(verbs, 2)

  male_name = False

  negations = None

  if random.uniform(0,1) < prob :
    noun_functions = random.sample(nouns, 2)
    type = "2_quantifiers"
    quantifiers = [random.choice(["all", "exists"]), random.choice(["all", "exists"])]
    variables = random.sample(nouns, 2)
      

    negations = {variables[0] : random.choice([True, False]), 
              variables[1] : random.choice([True, False]),
              verb_functions[0] : random.choice([True, False]),
              verb_functions[1] : random.choice([True, False])}

  else :
    quantifiers = [random.choice(["all", "exists"])]
 
    type = "PropN"

    variables = [random.choice(domain), random.choice(nouns)]
    negations = {variables[0] : False, 
                variables[1] : random.choice([True, False]),
                verb_functions[0] : random.choice([True, False]),
                verb_functions[1] : random.choice([True, False])}


  male_name = False if variables[0] in female_names else True


  logic = anaphora_generate_logic_str(quantifiers, variables, verb_functions, negations, type)
  sentence = natural_language_sentence_generation(quantifiers, variables, verb_functions, negations, type, male_name)

  return logic, sentence

def model_generation(domain, signature_n, signature_v, prob_n = 0.5, prob_v = 0.75):
  model = [(d, d) for d in domain]
  model.append(('people', set(domain)))
  for f in signature_n :
    sample = []
    for v in domain:
      if random.uniform(0, 1) <= prob_n :
        sample.append(v)
    model.append((f, set(sample)))

  for f in signature_v :
    sample = []
    for v_1 in domain:
      for v_2 in domain :
        if random.uniform(0, 1) <= prob_v :
          if random.uniform(0, 1) <= prob_v :
            sample.append((v_1, v_2))
    model.append((f, set(sample)))

  return model


def model_to_nl(model, nouns, verbs, domain):

  str_temp = ""
  

  for i in model:
    func = i[0]
    values = list(i[1])
    if func in domain :
      continue
    if func == "people":
        values_str = ""
        for str_val in values[:-1]:
          values_str += str_val + ", "
        
        str_temp += "{}and {} are people in the group. ".format(values_str, values[-1])

    if func in nouns:
      
      if len(values) == 0:
        str_temp += "There are no {}. ".format(func)
      elif len(values) == 1:
        str_temp += "{} is a {}. ".format(values[0], func)
      else :
        values_str = ""
        for str_val in values[:-1]:
          values_str += str_val + ", "
        str_temp += "{}and {} are {}. ".format(values_str, values[-1], func)

    elif func in verbs:

      if len(values) == 0:
        str_temp += "No one {} anyone. ".format(func)
      elif len(values) == 1:
        str_temp += "{} {} {}.".format(values[0][0], func, values[0][1])
      else :
        subj = {}
        for (v_1, v_2) in values:
          if v_1 not in subj:
            subj[v_1] = [v_2]
          else :
            subj[v_1].append(v_2)


        for sub in subj:
          values_str = ""
          if len(subj[sub]) == 1:
            str_temp += "{} {} {}.".format(sub, func, subj[sub][0])
          else :
            for val in subj[sub][:-1]:
              values_str += val + ", "
            str_temp += "{} {} {}and {}.".format(sub, func, values_str, subj[sub][-1])



  str_model = str_temp.replace(", and ", " and ")
  return str_model

def generate_datapoint(count_professions, verbs_set, names, domain_size = 5, signature_size = 4, max_count = 300, label = "random", prob = 0.85):

  #domain = random.sample(names, domain_size)
  domain = random.sample(names, random.randrange(2, domain_size))
  #nouns = random.sample(count_professions, random.randrange(3, signature_size + 2)) 
  nouns = random.sample(count_professions, signature_size)
  #vbs = random.sample(verbs_set, random.randrange(2,signature_size)) 
  vbs = random.sample(verbs_set, signature_size)

  logic, sentence = generate_sentence_anaphora(nouns, domain, vbs, prob)

  signature_n = nouns.copy()
  signature_v = vbs.copy()

  model_found = False
  model = None
  
  if label == "random":
    label = random.choice([True, False])


  counter = 0
  model_nl = None
  while(True):
    model = model_generation(domain, signature_n, signature_v)

    val = nltk.Valuation(model)
    dom = val.domain
    m = nltk.Model(dom, val)
    g = nltk.sem.Assignment(dom)

    validity = m.evaluate(logic, g)

    if validity == label:
      model_found = True
      model_nl = model_to_nl(model, nouns, vbs, domain)
      break
    elif counter > max_count:
      break
    counter += 1
  return logic, sentence, model, label, model_found, model_nl

def generate_data(count_professions, verbs, names, domain_size = 5, signature_size = 7, max_count = 300, total_num = 100000, propN_prob = 0.8):
  data = {
      'model' : [],
      'model_nl' : [],
      'sentence' : [],
      'logic' : [],
      'label' : []
  }

  count = 0
  model_not_found = 0

  count_false = 0
  count_truth = 0
  label = "random"

  prob = 0.85

  num_data_points = total_num

  while(count < num_data_points):
    logic, sentence, model, label, model_found, model_nl = generate_datapoint(count_professions, verbs, names, domain_size, signature_size, max_count, label, prob)
    if (model_nl == None) or ("There are no" in model_nl) or ("No one" in model_nl):
      model_not_found += 1
      continue
    else:
      if model_found :
        data['model'].append(model)
        data['sentence'].append(sentence)
        data['logic'].append(logic)
        data['label'].append(label)
        data['model_nl'].append(model_nl)
        count += 1
        if label == False:
          count_false += 1
        else :
          count_truth += 1
        
        if count_false >= num_data_points/2:
          label = True
        elif count_truth >= num_data_points/2:
          label = False
        else :
          label = "random"
      else :
        model_not_found += 1
    if (count % 20000) == 0 :
      print("{} data points are generated".format(count))  
  print("Number of times model did not generated: {}".format(model_not_found))

  df = pd.DataFrame(data)
  df['model'] = df['model'].astype(str)
  df = df.drop_duplicates(subset = ['sentence', 'model'], keep = 'first')

  return df

In [ ]:
df = generate_data(roles, verbs, names,total_num=40000)

20000 data points are generated
40000 data points are generated
Number of times model did not generated: 66918

In [ ]:
df.label.value_counts()

True     20000
False    20000
Name: label, dtype: int64

In [ ]:
df.tail()

,model,model_nl,sentence,logic,label
39995,"[('Mordechai', 'Mordechai'), ('Xavier', 'Xavie...","Xavier, Kinsley, Aliyah, Justin, Zahir, Franci...",a computer_scientist understand a non-paver wh...,exists x.(computer_scientist(x) & exists y.(-p...,True
39996,"[('Atreus', 'Atreus'), ('Jaden', 'Jaden'), ('B...","Jaden, Kennedy, Jairo, Heavenly, Riley, Madden...",every non-scorer serve a non-sailor who invest...,all x.(-scorer(x) -> exists y.(-sailor(y) & in...,True
39997,"[('Amy', 'Amy'), ('Roland', 'Roland'), ('Dougl...","Tenley, Colt, Miley, Kori, Douglas, Roland, He...",no non-fbi_agent approve every non-cynic who k...,all x.(-fbi_agent(x) -> exists y.(-cynic(y) & ...,True
39998,"[('Ivan', 'Ivan'), ('Mary', 'Mary'), ('Caden',...","Charlie, Mary, Rebekah, Tony, Ivan, Kendall, C...",no non-hairdresser pet every publisher who enc...,all x.(-hairdresser(x) -> exists y.(publisher(...,True
39999,"[('Mayson', 'Mayson'), ('Emily', 'Emily'), ('A...","Mayson, Marcelo, Jaxx, Salvador, Sam, Emily, A...",no non-helper impress every baker who touch her,all x.(-helper(x) -> exists y.(baker(y) & touc...,True

In [ ]:
df = df.sample(frac = 1)

In [ ]:

det_1_exists = 0
det_1_all = 0

for index, row in df.sample(10000).iterrows():
  if row["logic"].split()[0] == "exists" and row["label"] == True:
    det_1_exists += 1

  elif row["logic"].split()[0] == "all"  and row["label"] == True:
    det_1_all += 1

det_1_exists, det_1_all

(2647, 2381)

In [ ]:

df['model_nl'].str.split().apply(len).max()

190

In [ ]:
df.sample(10)

,model,model_nl,sentence,logic,label
1936,"[('Dior', 'Dior'), ('Azalea', 'Azalea'), ('Cai...","Emerie, Koda, Quinn, Sariyah, Presley, Salvato...",all non-visitor perceive every non-stunt_perfo...,all x.(-visitor(x) -> all y.(-stunt_performer(...,False
33836,"[('Phoenix', 'Phoenix'), ('Addyson', 'Addyson'...","Mallory, Everleigh, Gustavo, Sterling, Milan, ...",Amir examine every tennis_player who defend him,"all x.(tennis_player(x) & defend(x, Amir) -> e...",False
18736,"[('Priscilla', 'Priscilla'), ('Vihaan', 'Vihaa...","Hayden, Vihaan, Natalia, Enrique, Elsa, Phoebe...",no principal owe any captain who does not hit him,all x.(principal(x) -> all y.(captain(y) & -hi...,True
9443,"[('Connor', 'Connor'), ('Alisson', 'Alisson'),...","Chris, Devon, Jerry, Andrea, Gwen, Connor, Ali...",all ballerina dislike some non-physician who d...,all x.(ballerina(x) -> exists y.(-physician(y)...,True
11753,"[('Maxine', 'Maxine'), ('Bear', 'Bear'), ('Arl...","Zaylee, Oakley, Adonis, Wilder, Maggie, Bear, ...",no barber fight every non-conductor who does n...,all x.(barber(x) -> exists y.(-conductor(y) & ...,False
5876,"[('Charleigh', 'Charleigh'), ('Keyla', 'Keyla'...","Harmony, Waylon, Dorothy, Felicity, Misael, Al...",no ai_scientist notice every non-boxer who imp...,all x.(ai_scientist(x) -> exists y.(-boxer(y) ...,True
6288,"[('Genevieve', 'Genevieve'), ('Evelynn', 'Evel...","Zaid, Stephanie, Azariah, Tucker, London, Ayla...",London eat every interior_designer who does no...,"all x.(interior_designer(x) & -owe(x, London) ...",True
12458,"[('Bentlee', 'Bentlee'), ('Myra', 'Myra'), ('C...","Daniela, Colt, Morgan, Kenzie, Selah, Myra, Je...",no non-policeman notice any cio who eat her,"all x.(-policeman(x) -> all y.(cio(y) & eat(y,...",False
19541,"[('Lilith', 'Lilith'), ('Kathleen', 'Kathleen'...","Koda, Kathleen, Amy, Luca, Austyn, Lilith, Mac...",all non-fisherman approach all non-technician ...,all x.(-fisherman(x) -> all y.(-technician(y) ...,False
34379,"[('Pierce', 'Pierce'), ('Hazel', 'Hazel'), ('A...","Hazel, Aidan, Dario, Dominick, Nylah, Mac, Eli...",every cyclist pet some actor who criticize him,all x.(cyclist(x) -> exists y.(actor(y) & crit...,False

In [ ]:
df.shape

(40000, 5)

In [ ]:
df.tail(10)

,model,model_nl,sentence,logic,label
10045,"[('Wallace', 'Wallace'), ('Kaiser', 'Kaiser'),...","Juelz, Sebastian, Kaiser, Ailani, Savannah, Wa...",some non-cashier admire a non-taxi_driver who ...,exists x.(-cashier(x) & exists y.(-taxi_driver...,False
16380,"[('Sophie', 'Sophie'), ('Ada', 'Ada'), ('Brynn...","Sophie, Cecelia, Brynn, Kylo, Zoe, Ada and Leo...",all paver know a non-cto who fight them,all x.(paver(x) -> exists y.(-cto(y) & fight(y...,False
16630,"[('Madilyn', 'Madilyn'), ('Marissa', 'Marissa'...","Marissa, Keilani, Madilyn, Esperanza, Ari, Rut...",a cio prefer some non-scorer who do not accuse...,exists x.(cio(x) & exists y.(-scorer(y) & -acc...,True
19475,"[('Brecken', 'Brecken'), ('Lacey', 'Lacey'), (...","Cayson, Julissa, Lacey, Brecken, Amaia, Azalea...",Alejandra dislike some non-forester who do not...,"exists x.(-forester(x) & -doubt(x, Alejandra) ...",True
23039,"[('Daphne', 'Daphne'), ('Selah', 'Selah'), ('M...","Daphne, Dustin, Selah, Millie, Camila, Dixie a...",a non-accountant kill no non-settler who eat her,exists x.(-accountant(x) & exists y.(-settler(...,True
23848,"[('Tessa', 'Tessa'), ('Kristian', 'Kristian'),...","Kate, Emery, Rene, Kristian, Tessa, Zander and...",a farmer does not break every clerk who admire...,exists x.(farmer(x) & all y.(clerk(y) & admire...,True
486,"[('Annika', 'Annika'), ('Elina', 'Elina'), ('L...","Elina, Legacy, Ethan, Roy, Annika, Lyric and E...",Roy recognize some non-bartender who tolerate him,"exists x.(-bartender(x) & tolerate(x, Roy) & r...",False
3368,"[('Adelynn', 'Adelynn'), ('Jaden', 'Jaden'), (...","Morgan, Jaden, Adelynn, Maison, Daniel, Zoie a...",no non-baker impress any air_traffic_controlle...,all x.(-baker(x) -> all y.(air_traffic_control...,False
22353,"[('Abigail', 'Abigail'), ('Janiyah', 'Janiyah'...","Amayah, Janiyah, Queen, Paisleigh, Abigail, Al...",some quant do not draw all non-plumber who pro...,exists x.(quant(x) & all y.(-plumber(y) & prom...,True
28546,"[('Adelyn', 'Adelyn'), ('Sariah', 'Sariah'), (...","Ronnie, Joaquin, Sariah, Adelyn, Roy, Sienna a...",some non-policeman do not make every non-judge...,exists x.(-policeman(x) & all y.(-judge(y) & -...,True

In [ ]:
df.drop_duplicates(subset = ['sentence', 'model_nl'], keep = 'first')

,model,model_nl,sentence,logic,label
530919,"[('Eden', 'Eden'), ('Ivory', 'Ivory'), ('Remin...","Cali, Remington, Eden and Ivory are people in ...",no non-physicist persuade every pilot who does...,all x.(-physicist(x) -> exists y.(pilot(y) & -...,False
323176,"[('Gabriela', 'Gabriela'), ('Zakai', 'Zakai'),...","Zakai, Oakley and Gabriela are people in the g...",some non-truck_driver see every king who pet them,exists x.(-truck_driver(x) & all y.(king(y) & ...,False
592393,"[('Anson', 'Anson'), ('Sylvie', 'Sylvie'), ('p...",Sylvie and Anson are people in the group. Sylv...,all paver hate all station_master who do not f...,all x.(paver(x) -> all y.(station_master(y) & ...,True
230915,"[('Dylan', 'Dylan'), ('Callen', 'Callen'), ('J...","Callen, Kyree, Dylan and Jeffery are people in...",Jeffery does not shoot every stratergist who d...,"all x.(stratergist(x) & -follow(x, Jeffery) ->...",False
468983,"[('Maeve', 'Maeve'), ('Fallon', 'Fallon'), ('A...","Adalee, Fallon and Maeve are people in the gro...",some sheriff know no non-psychologist who does...,exists x.(sheriff(x) & exists y.(-psychologist...,True
...,...,...,...,...,...
120430,"[('Aidan', 'Aidan'), ('Yaritza', 'Yaritza'), (...","Sylas, Edison, Yaritza and Aidan are people in...",no non-astronomer eat every non-cio who does n...,all x.(-astronomer(x) -> exists y.(-cio(y) & -...,True
70872,"[('Gael', 'Gael'), ('Reece', 'Reece'), ('Aurel...","Reece, Gael and Aurelia are people in the grou...",some non-philosopher do not know all non-anima...,exists x.(-philosopher(x) & all y.(-animal_bre...,False
561827,"[('Neil', 'Neil'), ('Remi', 'Remi'), ('people'...",Remi and Neil are people in the group. Neil is...,every non-dentist surprise every poet who shoo...,all x.(-dentist(x) -> all y.(poet(y) & shoot(y...,True
436175,"[('Palmer', 'Palmer'), ('Haylee', 'Haylee'), (...",Palmer and Haylee are people in the group. Hay...,some photographer criticize a scribe who appre...,exists x.(photographer(x) & exists y.(scribe(y...,True
591975,"[('Jonas', 'Jonas'), ('Ruth', 'Ruth'), ('Ander...","Jonas, Aaliyah, Ruth and Anderson are people i...",every non-ai_scientist steal all non-adult who...,all x.(-ai_scientist(x) -> all y.(-adult(y) & ...,True

In [ ]:
from sklearn.model_selection import train_test_split

df = df.sample(frac = 1)
df.reset_index(inplace = True, drop = True)

train, test = train_test_split(df, test_size=100000, random_state=42)
train.reset_index(drop = True, inplace = True)
test.reset_index(drop = True, inplace = True)
df_100k = train.sample(100000)

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

In [ ]:
import os
os.chdir('/content/drive/My Drive/PhD/Model Checking')
%ls

all_fragments_1M_test_v1.csv
all_fragments_1M_train_v1.csv
all_fragments_500k_train_v1.csv
anaphora_100k_test_v2.csv
anaphora_100k_test_v3.csv
anaphora_100k_test_v4.csv
anaphora_100k_train_v2.csv
anaphora_100k_train_v3.csv
anaphora_100k_train_v4.csv
anaphora_1K_diag.csv
anaphora_40K_diag_1.csv
anaphora_40K_diag.csv
anaphora_40k_t1.csv
anaphora_500k_train_v2.csv
anaphora_500k_train_v3.csv
anaphora_500k_train_v4.csv
BERT/
relative_clauses_syllogistic_100k_test_v2.csv
relative_clauses_syllogistic_100k_test_v3.csv
relative_clauses_syllogistic_100k_test_v4.csv
relative_clauses_syllogistic_100k_test_v5.csv
relative_clauses_syllogistic_100k_train_v2.csv
relative_clauses_syllogistic_100k_train_v3.csv
relative_clauses_syllogistic_100k_train_v4.csv
relative_clauses_syllogistic_500k_train.csv
relative_clauses_syllogistic_500k_train_v2.csv
relative_clauses_syllogistic_500k_train_v3.csv
relative_clauses_syllogistic_500k_train_v4.csv
relative_clauses_syllogistic_500k_train_v5.csv
relative_transitive_verbs_100k_test_v1.csv
relative_transitive_verbs_100k_test_v2.csv
relative_transitive_verbs_100k_test_v3.csv
relative_transitive_verbs_100k_test_v4.csv
relative_transitive_verbs_100k_test_v5.csv
relative_transitive_verbs_100k_test_v6.csv
relative_transitive_verbs_100k_test_v7.csv
relative_transitive_verbs_100k_test_v8.csv
relative_transitive_verbs_100k_test_v9.csv
relative_transitive_verbs_100k_train_v6.csv
relative_transitive_verbs_100k_train_v7.csv
relative_transitive_verbs_100k_train_v8.csv
relative_transitive_verbs_500k_train_v5.csv
relative_transitive_verbs_500k_train_v6.csv
relative_transitive_verbs_500k_train_v7.csv
relative_transitive_verbs_500k_train_v8.csv
relative_transitive_verbs_500k_train_v9.csv
syllogistic_100k_test_v7.csv
syllogistic_100k_test_v8.csv
syllogistic_100k_train_v7.csv
syllogistic_500k_train_v7.csv
syllogistic_500k_train_v8.csv
syllogistic_domain_6.csv
syllogistic_domain_7.csv
T5/
test_trainer/
transitive_verbs_100k_test_v10.csv
transitive_verbs_100k_test_v7.csv
transitive_verbs_100k_test_v8.csv
transitive_verbs_100k_test_v9.csv
transitive_verbs_100k_train_v10.csv
transitive_verbs_100k_train_v9.csv
transitive_verbs_500k_train_v10.csv
transitive_verbs_500k_train_v7.csv
transitive_verbs_500k_train_v8.csv
transitive_verbs_500k_train_v9.csv

In [ ]:
train.to_csv('anaphora_500k_train_v4.csv', index=False)

In [ ]:
test.to_csv('anaphora_100k_test_v4.csv', index=False)

In [ ]:
df = df.sample(frac = 1)
df.to_csv('anaphora_40k_test_predicate_4.csv', index=False)

In [ ]:
det_dict = {'all' : {True : 0, False : 0},
            'a' : {True : 0, False : 0},
            'some' : {True : 0, False : 0},
            'every' :{True : 0, False : 0}}

quantifier_dict = {'all' : {True : 0, False : 0},
                   'exists' : {True : 0, False : 0}}




for index, row in df.iterrows():
  det = row['sentence'].split()[0]
  quantifier = row['logic'].split()[0]

  if (det in det_dict) and (row['sentence'].split()[-2] in det_dict) :
    det_dict[det][row['label']] += 1
    quantifier_dict[quantifier][row['label']] += 1


det_dict

{'a': {False: 0, True: 0},
 'all': {False: 0, True: 0},
 'every': {False: 0, True: 0},
 'some': {False: 0, True: 0}}

In [ ]:
quantifier_dict

{'all': {False: 14105, True: 14033}, 'exists': {False: 9213, True: 9545}}

In [ ]:
#df['model'] = df['model'].astype(str)

df.drop_duplicates(subset = ['sentence', 'model_nl'], keep = 'first')

                                                    model  ...  label
0       [('Blair', 'Blair'), ('Xiomara', 'Xiomara'), (...  ...   True
1       [('Alannah', 'Alannah'), ('Penny', 'Penny'), (...  ...  False
2       [('Kieran', 'Kieran'), ('Nellie', 'Nellie'), (...  ...   True
3       [('Alvaro', 'Alvaro'), ('Opal', 'Opal'), ('Alo...  ...   True
4       [('Nelson', 'Nelson'), ('Cannon', 'Cannon'), (...  ...  False
...                                                   ...  ...    ...
199995  [('Kenneth', 'Kenneth'), ('Otis', 'Otis'), ('A...  ...  False
199996  [('Rayan', 'Rayan'), ('Mekhi', 'Mekhi'), ('Ben...  ...   True
199997  [('Jair', 'Jair'), ('Leo', 'Leo'), ('people', ...  ...   True
199998  [('Langston', 'Langston'), ('Nadia', 'Nadia'),...  ...  False
199999  [('Itzayana', 'Itzayana'), ('Jabari', 'Jabari'...  ...  False

[200000 rows x 5 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/My Drive/PhD/Model Checking')
%ls

template_based_syllogistic_200k_nl.csv

In [ ]:
df.to_csv('template_based_transitive_200k_nl.csv', index=False)

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('template_based_transitive_200k_nl.csv', error_bad_lines=False)
df

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

                                                    model  ...  label
0       [('Blair', 'Blair'), ('Xiomara', 'Xiomara'), (...  ...   True
1       [('Alannah', 'Alannah'), ('Penny', 'Penny'), (...  ...  False
2       [('Kieran', 'Kieran'), ('Nellie', 'Nellie'), (...  ...   True
3       [('Alvaro', 'Alvaro'), ('Opal', 'Opal'), ('Alo...  ...   True
4       [('Nelson', 'Nelson'), ('Cannon', 'Cannon'), (...  ...  False
...                                                   ...  ...    ...
199995  [('Kenneth', 'Kenneth'), ('Otis', 'Otis'), ('A...  ...  False
199996  [('Rayan', 'Rayan'), ('Mekhi', 'Mekhi'), ('Ben...  ...   True
199997  [('Jair', 'Jair'), ('Leo', 'Leo'), ('people', ...  ...   True
199998  [('Langston', 'Langston'), ('Nadia', 'Nadia'),...  ...  False
199999  [('Itzayana', 'Itzayana'), ('Jabari', 'Jabari'...  ...  False

[200000 rows x 5 columns]

In [ ]:
df.tail(5)

                                                    model  ...  label
199995  [('people', {'Turner', 'Lionel', 'Emir', 'Joyc...  ...  False
199996  [('people', {'Cohen', 'Jermaine', 'Legend', 'H...  ...   True
199997  [('people', {'Bianca', 'Estrella'}), ('cleaner...  ...   True
199998  [('people', {'Dominick', 'Molly', 'Aliza', 'Al...  ...   True
199999  [('people', {'Juliana', 'Lailah'}), ('soldier'...  ...   True

[5 rows x 4 columns]

### Testing model checking function

In [ ]:
generate_datapoint(count_professions, emotion_adj, names)

['Berkley', 'Anais'] ['epidemiologist', 'optician', 'archeologist'] ['Gloomy', 'Mysterious']
['optician', 'archeologist']
a Noun ['optician', 'archeologist'] {'optician': False, 'archeologist': True}

('exists x.(optician(x) & -archeologist(x))',
 'a optician is not a archeologist',
 [('people', {'Anais', 'Berkley'}),
  ('epidemiologist', {'Anais', 'Berkley'}),
  ('optician', {'Berkley'}),
  ('archeologist', {'Anais'}),
  ('Gloomy', set()),
  ('Mysterious', {'Berkley'})],
 True,
 True)

In [ ]:
>>> import nltk
>>> from nltk.sem import Valuation, Model
v = [('adam', 'b1'), ('betty', 'g1'), ('fido', 'd1'),
... ('girl', set(['g1', 'g2'])), ('boy', set(['b1', 'b2'])),
... ('dog', set()),
... ('love', set([('b1', 'g1'), ('b2', 'g2'), ('g1', 'b1'), ('g2', 'b1')]))]

>>> val = Valuation(v)
>>> dom = val.domain
>>> m = Model(dom, val)

>>> dom = val.domain
>>> g = nltk.sem.Assignment(dom)
>>> m.evaluate('all x.(dog(x) -> love(x, betty))', g)

True

In [ ]:
template_syllogistic("neg_noun_adj_si"]

SyntaxError: ignored

In [ ]:
str_temp = ""

for i in v:
  func = i[0]
  values = list(i[1])
  print(values)

  if func == "people":
    values_str = ""
    for str_val in values[:-1]:
      values_str += str_val + ", "
    
    str_temp += "{}and {} are people in the group. ".format(values_str, values[-1])
  else :
    if len(values) == 0:
      str_temp += "There are no {}. ".format(func)
    elif len(values) == 1:
      str_temp += "{} is a {}. ".format(values[0], func)
    else :
      values_str = ""
      for str_val in values[:-1]:
        values_str += str_val + ", "
      str_temp += "{}and {} are {}. ".format(values_str, values[-1], func)

  str_temp = str_temp.replace(", and ", " and ")

['Khaleesi', 'Ellison', 'Joziah', 'Kaiser']
['Khaleesi', 'Joziah', 'Ellison']
['Khaleesi', 'Kaiser']
['Joziah']
['Khaleesi', 'Joziah', 'Kaiser']
['Khaleesi']
[]

In [ ]:
str_temp

'Khaleesi, Ellison, Joziah and Kaiser are people in the group. Khaleesi, Joziah and Ellison are machinist. Khaleesi and Kaiser are engineer. Joziah is a driller. Khaleesi, Joziah and Kaiser are Safe. Khaleesi is a Earnest. There are no Supportive. '