<a href="https://colab.research.google.com/github/iTharindu/reasoning-withing-a-structure/blob/main/Notebooks/Model_Checking_Transitive_verbs_Template_based.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
male_names = ['Liam', 'Noah', 'Oliver', 'William', 'Elijah', 'James', 'Benjamin', 'Lucas', 'Mason', 'Ethan', 'Alexander', 'Henry', 'Jacob', 'Michael', 'Daniel', 'Logan', 'Jackson', 'Sebastian', 'Jack', 'Aiden', 'Owen', 'Samuel', 'Matthew', 'Joseph', 'Levi', 'Mateo', 'David', 'John', 'Wyatt', 'Carter', 'Julian', 'Luke', 'Grayson', 'Isaac', 'Jayden', 'Theodore', 'Gabriel', 'Anthony', 'Dylan', 'Leo', 'Lincoln', 'Jaxon', 'Asher', 'Christopher', 'Josiah', 'Andrew', 'Thomas', 'Joshua', 'Ezra', 'Hudson', 'Charles', 'Caleb', 'Isaiah', 'Ryan', 'Nathan', 'Adrian', 'Christian', 'Maverick', 'Colton', 'Elias', 'Aaron', 'Eli', 'Landon', 'Jonathan', 'Nolan', 'Hunter', 'Cameron', 'Connor', 'Santiago', 'Jeremiah', 'Ezekiel', 'Angel', 'Roman', 'Easton', 'Miles', 'Robert', 'Jameson', 'Nicholas', 'Greyson', 'Cooper', 'Ian', 'Carson', 'Axel', 'Jaxson', 'Dominic', 'Leonardo', 'Luca', 'Austin', 'Jordan', 'Adam', 'Xavier', 'Jose', 'Jace', 'Everett', 'Declan', 'Evan', 'Kayden', 'Parker', 'Wesley', 'Kai', 'Brayden', 'Bryson', 'Weston', 'Jason', 'Emmett', 'Sawyer', 'Silas', 'Bennett', 'Brooks', 'Micah', 'Damian', 'Harrison', 'Waylon', 'Ayden', 'Vincent', 'Ryder', 'Kingston', 'Rowan', 'George', 'Luis', 'Chase', 'Cole', 'Nathaniel', 'Zachary', 'Ashton', 'Braxton', 'Gavin', 'Tyler', 'Diego', 'Bentley', 'Amir', 'Beau', 'Gael', 'Carlos', 'Ryker', 'Jasper', 'Max', 'Juan', 'Ivan', 'Brandon', 'Jonah', 'Giovanni', 'Kaiden', 'Myles', 'Calvin', 'Lorenzo', 'Maxwell', 'Jayce', 'Kevin', 'Legend', 'Tristan', 'Jesus', 'Jude', 'Zion', 'Justin', 'Maddox', 'Abel', 'King', 'Camden', 'Elliott', 'Malachi', 'Milo', 'Emmanuel', 'Karter', 'Rhett', 'Alex', 'August', 'River', 'Xander', 'Antonio', 'Brody', 'Finn', 'Elliot', 'Dean', 'Emiliano', 'Eric', 'Miguel', 'Arthur', 'Matteo', 'Graham', 'Alan', 'Nicolas', 'Blake', 'Thiago', 'Adriel', 'Victor', 'Joel', 'Timothy', 'Hayden', 'Judah', 'Abraham', 'Edward', 'Messiah', 'Zayden', 'Theo', 'Tucker', 'Grant', 'Richard', 'Alejandro', 'Steven', 'Jesse', 'Dawson', 'Bryce', 'Avery', 'Oscar', 'Patrick', 'Archer', 'Barrett', 'Leon', 'Colt', 'Charlie', 'Peter', 'Kaleb', 'Lukas', 'Beckett', 'Jeremy', 'Preston', 'Enzo', 'Luka', 'Andres', 'Marcus', 'Felix', 'Mark', 'Ace', 'Brantley', 'Atlas', 'Remington', 'Maximus', 'Matias', 'Walker', 'Kyrie', 'Griffin', 'Kenneth', 'Israel', 'Javier', 'Kyler', 'Jax', 'Amari', 'Zane', 'Emilio', 'Knox', 'Adonis', 'Aidan', 'Kaden', 'Paul', 'Omar', 'BrianPeter', 'Louis', 'Caden', 'Maximiliano', 'Holden', 'Paxton', 'Nash', 'Bradley', 'Bryan', 'Simon', 'Phoenix', 'Lane', 'Josue', 'Colin', 'Rafael', 'Kyle', 'Riley', 'Jorge', 'Beckham', 'Cayden', 'Jaden', 'Emerson', 'Ronan', 'Karson', 'Arlo', 'Tobias', 'Brady', 'Clayton', 'Francisco', 'Zander', 'Erick', 'Walter', 'Daxton', 'Martin', 'Damien', 'Dallas', 'Cody', 'Chance', 'Jensen', 'Finley', 'Jett', 'Corbin', 'Kash', 'Reid', 'Kameron', 'Andre', 'Gunner', 'Jake', 'Hayes', 'Manuel', 'Prince', 'Bodhi', 'Cohen', 'Sean', 'Khalil', 'Hendrix', 'Derek', 'Cristian', 'Cruz', 'Kairo', 'Dante', 'Atticus', 'Killian', 'Stephen', 'Orion', 'Malakai', 'Ali', 'Eduardo', 'Fernando', 'Anderson', 'Angelo', 'Spencer', 'Gideon', 'Mario', 'Titus', 'Travis', 'Rylan', 'Kayson', 'Ricardo', 'Tanner', 'Malcolm', 'Raymond', 'Odin', 'Cesar', 'Lennox', 'Joaquin', 'Kane', 'Wade', 'Muhammad', 'Iker', 'Jaylen', 'Crew', 'Zayn', 'Hector', 'Ellis', 'Leonel', 'Cairo', 'Garrett', 'Romeo', 'Dakota', 'Edwin', 'Warren', 'Julius', 'Major', 'Donovan', 'Caiden', 'Tyson', 'Nico', 'Sergio', 'Nasir', 'Rory', 'Devin', 'Jaiden', 'Jared', 'Kason', 'Malik', 'Jeffrey', 'Ismael', 'Elian', 'Marshall', 'Lawson', 'Desmond', 'Winston', 'Nehemiah', 'Ari', 'Conner', 'Jay', 'Kade', 'Andy', 'Johnny', 'Jayceon', 'Marco', 'Seth', 'Ibrahim', 'Raiden', 'Collin', 'Edgar', 'Erik', 'Troy', 'Clark', 'Jaxton', 'Johnathan', 'Gregory', 'Russell', 'Royce', 'Fabian', 'Ezequiel', 'Noel', 'Pablo', 'Cade', 'Pedro', 'Sullivan', 'Trevor', 'Reed', 'Quinn', 'Frank', 'Harvey', 'Princeton', 'Zayne', 'Matthias', 'Conor', 'Sterling', 'Dax', 'Grady', 'Cyrus', 'Gage', 'Leland', 'Solomon', 'Emanuel', 'Niko', 'Ruben', 'Kasen', 'Mathias', 'Kashton', 'Franklin', 'Remy', 'Shane', 'Kendrick', 'Shawn', 'Otto', 'Armani', 'Keegan', 'Finnegan', 'Memphis', 'Bowen', 'Dominick', 'Kolton', 'Jamison', 'Allen', 'Philip', 'Tate', 'Peyton', 'Jase', 'Oakley', 'Rhys', 'Kyson', 'Adan', 'Esteban', 'Dalton', 'Gianni', 'Callum', 'Sage', 'Alexis', 'Milan', 'Moises', 'Jonas', 'Uriel', 'Colson', 'Marcos', 'Zaiden', 'Hank', 'Damon', 'Hugo', 'Ronin', 'Royal', 'Kamden', 'Dexter', 'Luciano', 'Alonzo', 'Augustus', 'Kamari', 'Eden', 'Roberto', 'Baker', 'Bruce', 'Kian', 'Albert', 'Frederick', 'Mohamed', 'Abram', 'Omari', 'Porter', 'Enrique', 'Alijah', 'Francis', 'Leonidas', 'Zachariah', 'Landen', 'Wilder', 'Apollo', 'Santino', 'Tatum', 'Pierce', 'Forrest', 'Corey', 'Derrick', 'Isaias', 'Kaison', 'Kieran', 'Arjun', 'Gunnar', 'Rocco', 'Emmitt', 'Abdiel', 'Braylen', 'Maximilian', 'Skyler', 'Phillip', 'Benson', 'Cannon', 'Deacon', 'Dorian', 'Asa', 'Moses', 'Ayaan', 'Jayson', 'Raul', 'Briggs', 'Armando', 'Nikolai', 'Cassius', 'Drew', 'Rodrigo', 'Raphael', 'Danny', 'Conrad', 'Moshe', 'Zyaire', 'Julio', 'Casey', 'Ronald', 'Scott', 'Callan', 'Roland', 'Saul', 'Jalen', 'Brycen', 'Ryland', 'Lawrence', 'Davis', 'Rowen', 'Zain', 'Ermias', 'Jaime', 'Duke', 'Stetson', 'Alec', 'Yusuf', 'Case', 'Trenton', 'Callen', 'Ariel', 'Jasiah', 'Soren', 'Dennis', 'Donald', 'Keith', 'Izaiah', 'Lewis', 'Kylan', 'Kobe', 'Makai', 'Rayan', 'Ford', 'Zaire', 'Landyn', 'Roy', 'Bo', 'Chris', 'Jamari', 'Ares', 'Mohammad', 'Darius', 'Drake', 'Tripp', 'Marcelo', 'Samson', 'Dustin', 'Layton', 'Gerardo', 'Johan', 'Kaysen', 'Keaton', 'Reece', 'Chandler', 'Lucca', 'Mack', 'Baylor', 'Kannon', 'Marvin', 'Huxley', 'Nixon', 'Tony', 'Cason', 'Mauricio', 'Quentin', 'Edison', 'Quincy', 'Ahmed', 'Finnley', 'Justice', 'Taylor', 'Gustavo', 'Brock', 'Ahmad', 'Kyree', 'Arturo', 'Nikolas', 'Boston', 'Sincere', 'Alessandro', 'Braylon', 'Colby', 'Leonard', 'Ridge', 'Trey', 'Aden', 'Leandro', 'Sam', 'Uriah', 'Ty', 'Sylas', 'Axton', 'Issac', 'Fletcher', 'Julien', 'Wells', 'Alden', 'Vihaan', 'Jamir', 'Valentino', 'Shepherd', 'Keanu', 'Hezekiah', 'Lionel', 'Kohen', 'Zaid', 'Alberto', 'Neil', 'Denver', 'Aarav', 'Brendan', 'Dillon', 'Koda', 'Sutton', 'Kingsley', 'Sonny', 'Alfredo', 'Wilson', 'Harry', 'Jaziel', 'Salvador', 'Cullen', 'Hamza', 'Dariel', 'Rex', 'Zeke', 'Mohammed', 'Nelson', 'Boone', 'Ricky', 'Santana', 'Cayson', 'Lance', 'Raylan', 'Lucian', 'Eliel', 'Alvin', 'Jagger', 'Braden', 'Curtis', 'Mathew', 'Jimmy', 'Kareem', 'Archie', 'Amos', 'Quinton', 'Yosef', 'Bodie', 'Jerry', 'Langston', 'Axl', 'Stanley', 'Clay', 'Douglas', 'Layne', 'Titan', 'Tomas', 'Houston', 'Darren', 'Lachlan', 'Kase', 'Korbin', 'Leighton', 'Joziah', 'Samir', 'Watson', 'Colten', 'Roger', 'Shiloh', 'Tommy', 'Mitchell', 'Azariah', 'Noe', 'Talon', 'Deandre', 'Lochlan', 'Joe', 'Carmelo', 'Otis', 'Randy', 'Byron', 'Chaim', 'Lennon', 'Devon', 'Nathanael', 'Bruno', 'Aryan', 'Flynn', 'Vicente', 'Brixton', 'Kyro', 'Brennan', 'Casen', 'Kenzo', 'Orlando', 'Castiel', 'Rayden', 'Ben', 'Grey', 'Jedidiah', 'Tadeo', 'Morgan', 'Augustine', 'Mekhi', 'Abdullah', 'Ramon', 'Saint', 'Emery', 'Maurice', 'Jefferson', 'Maximo', 'Koa', 'Ray', 'Jamie', 'Eddie', 'Guillermo', 'Onyx', 'Thaddeus', 'Wayne', 'Hassan', 'Alonso', 'Dash', 'Elisha', 'Jaxxon', 'Rohan', 'Carl', 'Kelvin', 'Jon', 'Larry', 'Reese', 'Aldo', 'Marcel', 'Melvin', 'Yousef', 'Aron', 'Kace', 'Vincenzo', 'Kellan', 'Miller', 'Jakob', 'Reign', 'Kellen', 'Kristopher', 'Ernesto', 'Briar', 'Gary', 'Trace', 'Joey', 'Clyde', 'Enoch', 'Jaxx', 'Crosby', 'Magnus', 'Fisher', 'Jadiel', 'Bronson', 'Eugene', 'Lee', 'Brecken', 'Atreus', 'Madden', 'Khari', 'Caspian', 'Ishaan', 'Kristian', 'Westley', 'Hugh', 'Kamryn', 'Musa', 'Rey', 'Thatcher', 'Alfred', 'Emory', 'Kye', 'Reyansh', 'Yahir', 'Cain', 'Mordechai', 'Zayd', 'Demetrius', 'Harley', 'Felipe', 'Louie', 'Branson', 'Graysen', 'Allan', 'Kole', 'Harold', 'Alvaro', 'Harlan', 'Amias', 'Brett', 'Khalid', 'Misael', 'Westin', 'Zechariah', 'Aydin', 'Kaiser', 'Lian', 'Bryant', 'Junior', 'Legacy', 'Ulises', 'Bellamy', 'Brayan', 'Kody', 'Ledger', 'Eliseo', 'Gordon', 'London', 'Rocky', 'Valentin', 'Terry', 'Damari', 'Trent', 'Bentlee', 'Canaan', 'Gatlin', 'Kiaan', 'Franco', 'Eithan', 'Idris', 'Krew', 'Yehuda', 'Marlon', 'Rodney', 'Creed', 'Salvatore', 'Stefan', 'Tristen', 'Adrien', 'Jamal', 'Judson', 'Camilo', 'Kenny', 'Nova', 'Robin', 'Rudy', 'Van', 'Bjorn', 'Brodie', 'Mac', 'Jacoby', 'Sekani', 'Vivaan', 'Blaine', 'Ira', 'Ameer', 'Dominik', 'Alaric', 'Dane', 'Jeremias', 'Kyng', 'Reginald', 'Bobby', 'Kabir', 'Jairo', 'Alexzander', 'Benicio', 'Vance', 'Wallace', 'Zavier', 'Billy', 'Callahan', 'Dakari', 'Gerald', 'Turner', 'Bear', 'Jabari', 'Cory', 'Fox', 'Harlem', 'Jakari', 'Jeffery', 'Maxton', 'Ronnie', 'Yisroel', 'Zakai', 'Bridger', 'Remi', 'Arian', 'Blaze', 'Forest', 'Genesis', 'Jerome', 'Reuben', 'Wesson', 'Anders', 'Banks', 'Calum', 'Dayton', 'Kylen', 'Dangelo', 'Emir', 'Malakhi', 'Salem', 'Blaise', 'Tru', 'Boden', 'Kolten', 'Kylo', 'Aries', 'Henrik', 'Kalel', 'Landry', 'Marcellus', 'Zahir', 'Lyle', 'Dario', 'Rene', 'Terrance', 'Xzavier', 'Alfonso', 'Darian', 'Kylian', 'Maison', 'Foster', 'Keenan', 'Yahya', 'Heath', 'Javion', 'Jericho', 'Aziel', 'Darwin', 'Marquis', 'Mylo', 'Ambrose', 'Anakin', 'Jordy', 'Juelz', 'Toby', 'Yael', 'Azrael', 'Brentley', 'Tristian', 'Bode', 'Jovanni', 'Santos', 'Alistair', 'Braydon', 'Kamdyn', 'Marc', 'Mayson', 'Niklaus', 'Simeon', 'Colter', 'Davion', 'Leroy', 'Ayan', 'Dilan', 'Ephraim', 'Anson', 'Merrick', 'Wes', 'Will', 'Jaxen', 'Maxim', 'Howard', 'Jad', 'Jesiah', 'Ignacio', 'Zyon', 'Ahmir', 'Jair', 'Mustafa', 'Jermaine', 'Yadiel', 'Aayan', 'Dhruv', 'Seven']

    
female_names = ['Olivia', 'Emma', 'Ava', 'Sophia', 'Isabella', 'Charlotte', 'Amelia', 'Mia', 'Harper', 'Evelyn', 'Abigail', 'Emily', 'Ella', 'Elizabeth', 'Camila', 'Luna', 'Sofia', 'Avery', 'Mila', 'Aria', 'Scarlett', 'Penelope', 'Layla', 'Chloe', 'Victoria', 'Madison', 'Eleanor', 'Grace', 'Nora', 'Riley', 'Zoey', 'Hannah', 'Hazel', 'Lily', 'Ellie', 'Violet', 'Lillian', 'Zoe', 'Stella', 'Aurora', 'Natalie', 'Emilia', 'Everly', 'Leah', 'Aubrey', 'Willow', 'Addison', 'Lucy', 'Audrey', 'Bella', 'Nova', 'Brooklyn', 'Paisley', 'Savannah', 'Claire', 'Skylar', 'Isla', 'Genesis', 'Naomi', 'Elena', 'Caroline', 'Eliana', 'Anna', 'Maya', 'Valentina', 'Ruby', 'Kennedy', 'Ivy', 'Ariana', 'Aaliyah', 'Cora', 'Madelyn', 'Alice', 'Kinsley', 'Hailey', 'Gabriella', 'Allison', 'Gianna', 'Serenity', 'Samantha', 'Sarah', 'Autumn', 'Quinn', 'Eva', 'Piper', 'Sophie', 'Sadie', 'Delilah', 'Josephine', 'Nevaeh', 'Adeline', 'Arya', 'Emery', 'Lydia', 'Clara', 'Vivian', 'Madeline', 'Peyton', 'Julia', 'Rylee', 'Brielle', 'Reagan', 'Natalia', 'Jade', 'Athena', 'Maria', 'Leilani', 'Everleigh', 'Liliana', 'Melanie', 'Mackenzie', 'Hadley', 'Raelynn', 'Kaylee', 'Rose', 'Arianna', 'Isabelle', 'Melody', 'Eliza', 'Lyla', 'Katherine', 'Aubree', 'Adalynn', 'Kylie', 'Faith', 'Mary', 'Margaret', 'Ximena', 'Iris', 'Alexandra', 'Jasmine', 'Charlie', 'Amaya', 'Taylor', 'Isabel', 'Ashley', 'Khloe', 'Ryleigh', 'Alexa', 'Amara', 'Valeria', 'Andrea', 'Parker', 'Norah', 'Eden', 'Elliana', 'Brianna', 'Emersyn', 'Valerie', 'Anastasia', 'Eloise', 'Emerson', 'Cecilia', 'Remi', 'Josie', 'Alina', 'Reese', 'Bailey', 'Lucia', 'Adalyn', 'Molly', 'Ayla', 'Sara', 'Daisy', 'London', 'Jordyn', 'Esther', 'Genevieve', 'Harmony', 'Annabelle', 'Alyssa', 'Ariel', 'Aliyah', 'Londyn', 'Juliana', 'Morgan', 'Summer', 'Juliette', 'Trinity', 'Callie', 'Sienna', 'Blakely', 'Alaia', 'Kayla', 'Teagan', 'Alaina', 'Brynlee', 'Finley', 'Catalina', 'Sloane', 'Rachel', 'Lilly', 'Ember', 'Kimberly', 'Juniper', 'Sydney', 'Arabella', 'Gemma', 'Jocelyn', 'Freya', 'June', 'Lauren', 'Amy', 'Presley', 'Georgia', 'Journee', 'Elise', 'Rosalie', 'Ada', 'Laila', 'Brooke', 'Diana', 'Olive', 'River', 'Payton', 'Ariella', 'Daniela', 'Raegan', 'Alayna', 'Gracie', 'Mya', 'Blake', 'Noelle', 'Ana', 'Leila', 'Paige', 'Lila', 'Nicole', 'Rowan', 'Hope', 'Ruth', 'Alana', 'Selena', 'Marley', 'Kamila', 'Alexis', 'Mckenzie', 'Zara', 'Millie', 'Magnolia', 'Kali', 'Kehlani', 'Catherine', 'Maeve', 'Adelyn', 'Sawyer', 'Elsie', 'Lola', 'Jayla', 'Adriana', 'Journey', 'Vera', 'Aspen', 'Joanna', 'Alivia', 'Angela', 'Dakota', 'Camille', 'Nyla', 'Tessa', 'Brooklynn', 'Malia', 'Makayla', 'Rebecca', 'Fiona', 'Mariana', 'Lena', 'Julianna', 'Vanessa', 'Juliet', 'Camilla', 'Kendall', 'Harley', 'Cali', 'Evangeline', 'Mariah', 'Jane', 'Zuri', 'Elaina', 'Sage', 'Amira', 'Adaline', 'Lia', 'Charlee', 'Delaney', 'Lilah', 'Miriam', 'Angelina', 'Mckenna', 'Aniyah', 'Phoebe', 'Michelle', 'Thea', 'Hayden', 'Maggie', 'Lucille', 'Amiyah', 'Annie', 'Alexandria', 'Myla', 'Vivienne', 'Kiara', 'Alani', 'Margot', 'Adelaide', 'Briella', 'Brynn', 'Saylor', 'Destiny', 'Amari', 'Evelynn', 'Haven', 'Phoenix', 'Izabella', 'Kaia', 'Lilliana', 'Harlow', 'Alessandra', 'Madilyn', 'Nina', 'Logan', 'Adelynn', 'Amina', 'Kate', 'Fatima', 'Samara', 'Winter', 'Giselle', 'Evie', 'Arielle', 'Jessica', 'Talia', 'Leia', 'Gabriela', 'Gracelyn', 'Lexi', 'Laura', 'Makenzie', 'Melissa', 'Royalty', 'Rylie', 'Raelyn', 'Gabrielle', 'Paris', 'Daleyza', 'Joy', 'Maisie', 'Oakley', 'Ariyah', 'Kailani', 'Alayah', 'Stephanie', 'Amora', 'Willa', 'Gracelynn', 'Elle', 'Keira', 'Tatum', 'Veronica', 'Milani', 'Felicity', 'Paislee', 'Allie', 'Nylah', 'Ariah', 'Cassidy', 'Lyric', 'Madeleine', 'Miracle', 'Gwendolyn', 'Octavia', 'Dahlia', 'Heidi', 'Celeste', 'Remington', 'Makenna', 'Everlee', 'Scarlet', 'Esmeralda', 'Maci', 'Lainey', 'Jacqueline', 'Kira', 'Lana', 'Brinley', 'Demi', 'Ophelia', 'Lennon', 'Reign', 'Bristol', 'Sabrina', 'Alaya', 'Jennifer', 'Kenzie', 'Angel', 'Luciana', 'Anaya', 'Hallie', 'Ryan', 'Camryn', 'Kinley', 'Daniella', 'Lilith', 'Blair', 'Amanda', 'Collins', 'Jordan', 'Maliyah', 'Rosemary', 'Cataleya', 'Kaylani', 'Gia', 'Alison', 'Leighton', 'Nadia', 'Sutton', 'Carolina', 'Skye', 'Alicia', 'Regina', 'Viviana', 'Yaretzi', 'Heaven', 'Serena', 'Raven', 'Emely', 'Carmen', 'Wren', 'Helen', 'Charleigh', 'Danielle', 'Daphne', 'Esme', 'Nayeli', 'Maddison', 'Sarai', 'Dylan', 'Frances', 'Elisa', 'Mabel', 'Skyler', 'Jenna', 'Emelia', 'Kaitlyn', 'Miranda', 'Marlee', 'Matilda', 'Selah', 'Jolene', 'Wynter', 'Hattie', 'Bianca', 'Haley', 'Lorelei', 'Mira', 'Braelynn', 'Annalise', 'Madelynn', 'Katie', 'Palmer', 'Aylin', 'Elliott', 'Kyla', 'Rory', 'Avianna', 'Liana', 'Shiloh', 'Kalani', 'Jada', 'Kelsey', 'Elianna', 'Jimena', 'Kora', 'Kamryn', 'Ainsley', 'Averie', 'Kensley', 'Helena', 'Holly', 'Emory', 'Macie', 'Amber', 'Zariah', 'Erin', 'Eve', 'Kathryn', 'Renata', 'Kayleigh', 'Emmy', 'Celine', 'Francesca', 'Fernanda', 'April', 'Shelby', 'Poppy', 'Colette', 'Meadow', 'Nia', 'Sierra', 'Cheyenne', 'Edith', 'Oaklynn', 'Kennedi', 'Abby', 'Danna', 'Jazlyn', 'Alessia', 'Mikayla', 'Alondra', 'Addilyn', 'Leona', 'Mckinley', 'Carter', 'Maren', 'Sylvia', 'Alejandra', 'Ariya', 'Astrid', 'Adrianna', 'Charli', 'Imani', 'Maryam', 'Christina', 'Stevie', 'Maia', 'Adelina', 'Dream', 'Aisha', 'Alanna', 'Itzel', 'Azalea', 'Katelyn', 'Kylee', 'Leslie', 'Madilynn', 'Myra', 'Virginia', 'Remy', 'Hanna', 'Aleah', 'Jaliyah', 'Antonella', 'Aviana', 'Cameron', 'Chelsea', 'Cecelia', 'Alia', 'Mae', 'Cadence', 'Emberly', 'Charley', 'Janelle', 'Mallory', 'Kaliyah', 'Elaine', 'Gloria', 'Jayleen', 'Lorelai', 'Malaysia', 'Bethany', 'Briana', 'Beatrice', 'Dorothy', 'Rosie', 'Jemma', 'Noa', 'Carly', 'Mariam', 'Anne', 'Karina', 'Emmalyn', 'Ivory', 'Ivanna', 'Jamie', 'Kara', 'Aitana', 'Jayda', 'Justice', 'Meredith', 'Briar', 'Skyla', 'Khaleesi', 'Dayana', 'Julieta', 'Katalina', 'Kendra', 'Oaklyn', 'Ashlyn', 'Armani', 'Jazmin', 'Kyra', 'Angelica', 'Zahra', 'Dallas', 'Johanna', 'Elliot', 'Macy', 'Monroe', 'Kimber', 'Henley', 'Ari', 'Karsyn', 'Lyanna', 'Lilian', 'Amalia', 'Nola', 'Dior', 'Aleena', 'Megan', 'Michaela', 'Amirah', 'Cassandra', 'Melany', 'Legacy', 'Reyna', 'Alma', 'Emmie', 'Melina', 'Siena', 'Priscilla', 'Ashlynn', 'Savanna', 'Sloan', 'Tiana', 'Aubrie', 'Coraline', 'Reina', 'Allyson', 'Kaydence', 'Sasha', 'Julie', 'Alexia', 'Irene', 'Marilyn', 'Greta', 'Braelyn', 'Emerie', 'Lylah', 'Nalani', 'Monica', 'Aileen', 'Lauryn', 'Anahi', 'Aurelia', 'Kassidy', 'Rayna', 'Romina', 'Lillie', 'Marie', 'Rosa', 'Saige', 'Bonnie', 'Kelly', 'Xiomara', 'Annabella', 'Avah', 'Lacey', 'Anya', 'Liberty', 'Karen', 'Mercy', 'Zelda', 'Baylee', 'Chaya', 'Kenna', 'Roselyn', 'Liv', 'Mara', 'Ensley', 'Malani', 'Malaya', 'Hadassah', 'Lyra', 'Adley', 'Galilea', 'Jaylah', 'Karla', 'Nala', 'Opal', 'Aliza', 'Milena', 'Ailani', 'Louisa', 'Mina', 'Kairi', 'Clementine', 'Louise', 'Maleah', 'Janiyah', 'Marina', 'Anika', 'Julissa', 'Bailee', 'Hayley', 'Jessie', 'Laney', 'Eileen', 'Faye', 'Kynlee', 'Tiffany', 'Lara', 'Angie', 'Joelle', 'Rhea', 'Calliope', 'Jazmine', 'Amani', 'Haylee', 'Aliana', 'Leyla', 'Jolie', 'Kinslee', 'Ryann', 'Simone', 'Milan', 'Lennox', 'Treasure', 'Alora', 'Ellis', 'Rebekah', 'Mikaela', 'Lina', 'Harmoni', 'Yareli', 'Giuliana', 'Lea', 'Harlee', 'Elyse', 'Frida', 'Blaire', 'Aya', 'Laurel', 'Meghan', 'Pearl', 'Zaylee', 'Alena', 'Holland', 'Bria', 'Rayne', 'Bridget', 'Zariyah', 'Kori', 'Frankie', 'Clarissa', 'Brylee', 'Davina', 'Rivka', 'Cynthia', 'Zaria', 'Madalyn', 'Paula', 'Salem', 'Amelie', 'Madisyn', 'Vienna', 'Haisley', 'Ainhoa', 'Journi', 'Karter', 'Oaklee', 'Livia', 'Miley', 'Adele', 'Amaia', 'Yara', 'Averi', 'Emmeline', 'Kyleigh', 'Princess', 'Penny', 'Sariyah', 'Amayah', 'Crystal', 'Keyla', 'Lilyana', 'Linda', 'Aniya', 'Marianna', 'Alaiya', 'Noemi', 'Chanel', 'Estella', 'Isabela', 'Jillian', 'Kallie', 'Ellianna', 'Elsa', 'Itzayana', 'Zora', 'Estelle', 'Chana', 'Raina', 'Royal', 'Sunny', 'Estrella', 'Martha', 'Ellen', 'Kailey', 'Maxine', 'Clare', 'Teresa', 'Annika', 'Kamilah', 'Azariah', 'Della', 'Addyson', 'Kai', 'Lilianna', 'Tinsley', 'Yaritza', 'Navy', 'Winnie', 'Andi', 'Kamiyah', 'Waverly', 'Sky', 'Amaris', 'Ramona', 'Saoirse', 'Hana', 'Judith', 'Halle', 'Laylah', 'Novalee', 'Jaycee', 'Zaniyah', 'Alianna', 'Paulina', 'Jayde', 'Thalia', 'Giovanna', 'Gwen', 'Iliana', 'Elora', 'Ezra', 'Kaylie', 'Braylee', 'Mavis', 'Ellison', 'Margo', 'Mylah', 'Paisleigh', 'Analia', 'August', 'Brittany', 'Kaisley', 'Belen', 'Promise', 'Amiya', 'Dalary', 'Veda', 'Alisson', 'Keilani', 'Oakleigh', 'Guadalupe', 'Leanna', 'Rosalyn', 'Selene', 'Theodora', 'Kamari', 'Anais', 'Elodie', 'Celia', 'Dani', 'Hunter', 'Indie', 'Kenia', 'Nellie', 'Belle', 'Kataleya', 'Lexie', 'Miah', 'Rylan', 'Sylvie', 'Valery', 'Addilynn', 'Dulce', 'Marissa', 'Meilani', 'Natasha', 'Jaylee', 'Kimora', 'Raquel', 'Scarlette', 'Aliya', 'Nataly', 'Whitney', 'Corinne', 'Denver', 'Nathalie', 'Kiera', 'Milana', 'Vada', 'Violeta', 'Luz', 'Addisyn', 'Casey', 'Deborah', 'Tori', 'Zainab', 'Erika', 'Jenesis', 'Avalynn', 'Nancy', 'Emmalynn', 'Hadlee', 'Heavenly', 'Aubrielle', 'Elisabeth', 'Salma', 'Adalee', 'Landry', 'Malayah', 'Novah', 'Egypt', 'Ayleen', 'Blessing', 'Elina', 'Joyce', 'Myah', 'Zoie', 'Christine', 'Jaelynn', 'Persephone', 'Chandler', 'Emmaline', 'Paloma', 'Harleigh', 'Noor', 'Paola', 'India', 'Madalynn', 'Rosalee', 'Florence', 'Maliah', 'Flora', 'Luella', 'Patricia', 'Whitley', 'Carolyn', 'Kathleen', 'Keily', 'Kiana', 'Tenley', 'Alyson', 'Barbara', 'Dana', 'Yasmin', 'Bexley', 'Micah', 'Tatiana', 'Arden', 'Aubriella', 'Lindsey', 'Emani', 'Hailee', 'Lisa', 'Sevyn', 'Fallon', 'Magdalena', 'Tinley', 'Halo', 'Lailah', 'Arlette', 'Ansley', 'Esperanza', 'Cleo', 'Aila', 'Emerald', 'Jaelyn', 'Karlee', 'Kaya', 'Ingrid', 'Jewel', 'Emilee', 'Giana', 'Paityn', 'Zola', 'Amoura', 'Renee', 'Ann', 'Berkley', 'Harriet', 'Queen', 'Sariah', 'Beatrix', 'Sandra', 'Alannah', 'Austyn', 'Freyja', 'Kaylin', 'Samira', 'Taliyah', 'Hadleigh', 'Kaiya', 'Robin', 'Luisa', 'Zendaya', 'Ariadne', 'Dixie']

names = male_names + female_names

colors = [
    "Red","Orange","Yellow","Green","Blue","Purple",
    "Tan","Turquoise","Silver","Pink","Gray",
]

emotion_adj = [    
    "Accepting","Accommodating","Afraid","Aggressive","Agitated","Alarmed","Amazed",
    "Amused","Antagonistic","Anxious","Apathetic","Apprehensive","Arrogant","Bothered","Brave","Calm","Charming",
    "Cheerful","Competitive","Confident","Conscientious","Conservative","Creative","Curious",
    "Cynical","Distracted","Distraught","Distressed","Downcast",
    "Earnest","Gloomy","Grouchy","Guilty","Heroic","Hopeful",
    "Hostile","Humble","Jovial","Joyful","Jumpy","Mysterious","Opinionated",
    "Panicky","Passionate","Patient","Quarrelsome","Rational","Reasonable",
    "Sad","Safe","Scared","Scornful","Selfish",
    "Thoughtful","Tolerant","Tranquil","Treacherous","Welcoming","Witty","Zealous","Zany",
    "Supportive","Sardonic","Secretive","Bitter",
]

roles = [
    "actor","artist","butler","crook","director",
    "expert","fisherman","judge","juror","painter","musician",
    "policeman","fireman","professor","sheriff","soldier","student",
    "philosopher","teacher","tourist","lawyer","physician","engineer",
    "veterinarian","dentist","accountant","technician","electrician",
    "psychologist","physicist","plumber","waiter","mechanic","cook",
    "librarian","hairdresser","economist","bartender","cashier","surgeon",
    "pilot","butcher","optician","athlete","cleaner",
    "actuary","sailor","therapist","secret_agent","animal_breeder","air_traffic_controller",
    "athropologist","animal_trainer","allergist","real_estate_agent","archeologist",
    "astronomer","athletic_trainer","audiologist","auditor","bailiff",
    "baker","barber","clerk","cartographer","chiropractor","dancer","epidemiologist",
    "farmer","floral_designer","forester","truck_driver","jeweler","interior_designer",
    "machinist","mathematician","secretary","photographer","radio_announcer","roofer",
    "paver","taxi_driver","historian","poet","stunt_performer","monologist","publisher",
    "scribe","blogger","copy_editor","ceo","ticket_controller","station_master","surveyor",
    "driller", "scholar", "quant", "cfo" , "cto", "cio", "computer_scientist", "prisoner", 
    "guest", "visitor", "helper", "breadwinner", "host", "ghost", "playmaker", "scorer", 
    "settler", "reacher", "cynic", "witch", "captain", "buisness_analyst", "data_scientist",
    "trader", "principal", "ballerina", "footballer", "cricketer", "tennis_player", "lecturer", 
    "patient", "ai_scientist", "philosopher", "cyclist", "chess_player", "stratergist", 
    "scientist", "parent", "fbi_agent", "defender" , "attacker", "warlord", "nlp_engineer", 
    "grandmaster", "master", "king", "queen", "knight", "prince", "princess", "baby", "adult",
    "advisor", "wrestler", "fighter", "boxer", "bee_keeper", "musian", "dj_artist", "violinist",
    "conductor", "gymnast"
]

count_furniture = [
    "chair","table","desk","stool","couch","bookcase",
    "bed","mattress","dresser","futon","nightstand","storage_container",
    "hammock","billiard_table","piano","chess_board","door",
]


count_animals = [
    "aardvark","dog","alpaca","armadillo","anteater","penguin",
    "ant","bear","bonobo","beaver","bird","owl","butterfly",
    "buffalo","bumblebee","frog","whale","bison","badger","baboon",
    "rhinoceros","camel","cat","chicken","cheetah","cockatoo","cow","crab",
    "catepillar","chimpanzee","loon","spider","crocodile","coyote","chincilla",
    "duck","deer","dolphin","dingo","donkey","eel","elephant","emu","gorilla","falcon",
    "fox","ferret","gerbil","grasshopper","gopher","goat","hyena","horse","hippopotamus",
    "jaguar","kangaroo","lemur","lion","lynx","lizard","marmot","mink","muskrat","mouse",
    "macaw","moose","newt","ostrich","otter","pig","puffin","puma","pelican","peacock",
    "rabbit","snake","reindeer","raccoon","rat","sheep","vulture","wombat","wolf","warthog",
    "walrus","weasel","boar","zebra","seal",
]

verbs = ["like", "admire", "pet", "make", "break", "hit", "eat", "kill", "fight", "steal", "touch",
         "approve", "defend", "replace", "chase", "hunt", "dislike", "recognize", "understand", "feel",
         "love", "hate", "impress", "know", "notice", "perceive", "see", "remember", "surprise", "prefer",
         "draw", "accuse", "adore", "advise", "appreciate", "approach", "astonish", "need", "call", "believe",
         "follow", "serve", "consult", "convince", "criticize", "desire", "doubt", "encourage", "examine",
         "feed", "forgive", "hug", "investigate", "kiss", "mention", "owe", "persuade", "propose", "promise",
         "punch", "shoot", "threaten", "tolerate", "warn"]

In [ ]:
from nltk import *
from nltk.sem.drt import DrtParser
from nltk.sem import logic
import nltk
from nltk.sem import Expression
from nltk import load_parser
from nltk.sem import Valuation, Model
from nltk.corpus import brown


import random
import re

import numpy as np
import pandas as pd

from nltk.parse.generate import generate

import inflect

plural = inflect.engine()

In [ ]:
def generate_logic(quantifiers, noun_functions, verb_function, negations, type):
  noun_functions = ["-"+x if negations[x] else x for x in noun_functions]
  verb_function = "-"+verb_function if negations[verb_function] else verb_function

  
  if type == "2_variable":
    if quantifiers == ["all", "all"]:
      return "all x.({}(x) -> all y.({}(y) -> {}(x, y)))".format(noun_functions[0], noun_functions[1], verb_function)
    elif quantifiers == ["all", "exists"]:
      return "all x.({}(x) -> exists y.({}(y) & {}(x, y)))".format(noun_functions[0], noun_functions[1], verb_function)
    elif quantifiers == ["exists", "all"]:
      return "exists x.({}(x) & all y.({}(y) -> {}(x, y)))".format(noun_functions[0], noun_functions[1], verb_function)
    elif quantifiers == ["exists", "exists"]:
      return "exists x.({}(x) & exists y.({}(y) & {}(x, y)))".format(noun_functions[0], noun_functions[1], verb_function)

  elif type == "0_assign":
    if quantifiers == ["all"]:
      return "all x.({}(x) -> {}({}, x))".format(noun_functions[1], verb_function, noun_functions[0])
    elif quantifiers == ["exists"]:
      return "exists x.({}(x) & {}({}, x))".format(noun_functions[1], verb_function, noun_functions[0])

  elif type == "1_assign":
    if quantifiers == ["all"]:
      return "all x.({}(x) -> {}(x, {}))".format(noun_functions[0], verb_function, noun_functions[1])
    elif quantifiers == ["exists"]:
      return "exists x.({}(x) & {}(x, {}))".format(noun_functions[0], verb_function, noun_functions[1])

def template_transitive(template_name):
  templates = {
      "noun_verb_noun": "{} {} {} {} {}",
      "noun_verb_neg_noun": "{} {} {} {} non-{}",
      "noun_neg_verb_noun": "{} {} does not {} {} {}",
      "noun_neg_verb_neg_noun": "{} {} does not {} {} non-{}",
      "neg_noun_verb_noun": "{} non-{} {} {} {}",
      "neg_noun_verb_neg_noun": "{} non-{} {} {} non-{}",
      "neg_noun_neg_verb_noun": "{} non-{} does not {} {} {}",
      "neg_noun_neg_verb_neg_noun": "{} non-{} does not {} {} non-{}",
      "propn_verb_noun": "{} {} {} {}",
      "propn_verb_neg_noun": "{} {} {} non-{}",
      "propn_neg_verb_noun": "{} does not {} {} {}",
      "propn_neg_verb_neg_noun": "{} does not {} {} non-{}",
      "noun_verb_propn" : "{} {} {} {}",
      "noun_neg_verb_propn" : "{} {} does not {} {}",
      "neg_noun_verb_propn" : "{} non-{} {} {}",
      "neg_noun_neg_verb_propn" : "{} non-{} does not {} {}"
  }
  
  return templates[template_name]

def quantifier_det(quantifier):
  det = None
  if quantifier == "all":
    det = random.choice(["all", "every"])
  elif quantifier == "exists":
    det = random.choice(["some", "a"])
  elif quantifier == "- all":
    det = "no"
  elif quantifier == "- exists":
    det = "not all"

  return det

def natural_language_sentence_generation_transitive(quantifiers, noun_functions, verb_function, negations, type):
  dets = [quantifier_det(quantifier) for quantifier in quantifiers]

  negs = [negations[noun_functions[0]], negations[verb_function], negations[noun_functions[1]]]
  if type == "2_variable":
    if negs == [False, False, False]:
      return template_transitive("noun_verb_noun").format(dets[0], noun_functions[0], verb_function, dets[1], noun_functions[1])
    elif negs == [False, False, True]:
      return template_transitive("noun_verb_neg_noun").format(dets[0], noun_functions[0], verb_function, dets[1], noun_functions[1])
    elif negs == [False, True, False]:
      return template_transitive("noun_neg_verb_noun").format(dets[0], noun_functions[0], verb_function, dets[1], noun_functions[1])
    elif negs == [False, True, True]:
      return template_transitive("noun_neg_verb_neg_noun").format(dets[0], noun_functions[0], verb_function, dets[1], noun_functions[1])
    elif negs == [True, False, False]:
      return template_transitive("neg_noun_verb_noun").format(dets[0], noun_functions[0], verb_function, dets[1], noun_functions[1])
    elif negs == [True, False, True]:
      return template_transitive("neg_noun_verb_neg_noun").format(dets[0], noun_functions[0], verb_function, dets[1], noun_functions[1])
    elif negs == [True, True, False]:
      return template_transitive("neg_noun_neg_verb_noun").format(dets[0], noun_functions[0], verb_function, dets[1], noun_functions[1])
    elif negs == [True, True, True]:
      return template_transitive("neg_noun_neg_verb_neg_noun").format(dets[0], noun_functions[0], verb_function, dets[1], noun_functions[1])
  elif type == "0_assign":
    if negs == [False, False, False]:
      return template_transitive("propn_verb_noun").format(noun_functions[0], verb_function, dets[0], noun_functions[1])
    elif negs == [False, False, True]:
      return template_transitive("propn_verb_neg_noun").format(noun_functions[0], verb_function, dets[0], noun_functions[1])
    elif negs == [False, True, False]:
      return template_transitive("propn_neg_verb_noun").format(noun_functions[0], verb_function, dets[0], noun_functions[1])
    elif negs == [False, True, True]:
      return template_transitive("propn_neg_verb_neg_noun").format(noun_functions[0], verb_function, dets[0], noun_functions[1])
  elif type == "1_assign":
    if negs == [False, False, False]:
      return template_transitive("noun_verb_propn").format(dets[0], noun_functions[0], verb_function, noun_functions[1])
    elif negs == [False, True, False]:
      return template_transitive("noun_neg_verb_propn").format(dets[0], noun_functions[0], verb_function, noun_functions[1])
    elif negs == [True, False, False]:
      return template_transitive("neg_noun_verb_propn").format(dets[0], noun_functions[0], verb_function, noun_functions[1])
    elif negs == [True, True, False]:
      return template_transitive("neg_noun_neg_verb_propn").format(dets[0], noun_functions[0], verb_function, noun_functions[1])
  return 

def post_processing(sentence, quantifiers):
  if sentence.split()[0] in ["all", "every"]:
    if "does not" in sentence:
      sent_list = sentence.split()
      sent_list[0] = "no"
      sent = " ".join(sent_list)
      sent = sent.replace(" every ", " any ")
      sent = sent.replace(" all ", " any ")
      sent = sent.replace(" some ", " every ")
      sent = sent.replace(" a ", " every ")
      sent = sent.replace(" does not ", " ")


      return sent
  
  if quantifiers == ["exists", "exists"]:
    if "does not" in sentence:
      sent = sentence.replace(" some ", " no ")
      sent = sentence.replace(" a ", " no ")
      sent_list = sent.split()
      sent_list[0] = random.choice(["some", "a"])
      sent = " ".join(sent_list)
      sent = sent.replace(" does not ", " ")


      return sent
      
  if sentence.split()[0] in ["all", "some"]:
    return sentence.replace(" does not ", " do not ")

  return sentence


def generate_sentence_transitive_verbs(count_professions, verbs, names, prob = 0.75):
  type = None
  verb_function = random.choice(verbs)
  if random.uniform(0,1) < prob :
    noun_functions = random.sample(count_professions, 2)
    type = "2_variable"
    quantifiers = [random.choice(["all", "exists"]), random.choice(["all", "exists"])]
    negations = {noun_functions[0] : random.choice([True, False]), 
               noun_functions[1] : random.choice([True, False]),
               verb_function : random.choice([True, False])}
  else :
    prop_place = random.choice([0,1])
    quantifiers = [random.choice(["all", "exists"])]
    if prop_place == 0:
      noun_functions = [random.choice(names), random.choice(count_professions)]
      type = "0_assign"
      negations = {noun_functions[0] : False, 
               noun_functions[1] : random.choice([True, False]),
               verb_function : random.choice([True, False])}
      
    else :
      noun_functions = [random.choice(count_professions), random.choice(names)]
      type = "1_assign"
      negations = {noun_functions[0] : random.choice([True, False]), 
               noun_functions[1] : False,
               verb_function : random.choice([True, False])}

  logic = generate_logic(quantifiers, noun_functions, verb_function, negations, type)
  sentence = natural_language_sentence_generation_transitive(quantifiers, noun_functions, verb_function, negations, type)
  sentence = post_processing(sentence, quantifiers)
  return logic, sentence

def model_generation(domain, signature_n, signature_v, prob_n = 0.5, prob_v = 0.75):
  model = [(d, d) for d in domain]
  model.append(('people', set(domain)))
  for f in signature_n :
    sample = []
    for v in domain:
      if random.uniform(0, 1) <= prob_n :
        sample.append(v)
    model.append((f, set(sample)))

  for f in signature_v :
    sample = []
    for v_1 in domain:
      for v_2 in domain :
        if random.uniform(0, 1) <= prob_v :
          if random.uniform(0, 1) <= prob_v :
            sample.append((v_1, v_2))
    model.append((f, set(sample)))

  return model

def model_to_nl(model, nouns, verbs, domain):

  str_temp = ""
  

  for i in model:
    func = i[0]
    values = list(i[1])
    if func in domain :
      continue
    if func == "people":
        values_str = ""
        for str_val in values[:-1]:
          values_str += str_val + ", "
        
        str_temp += "{}and {} are people in the group. ".format(values_str, values[-1])

    if func in nouns:
      
      if len(values) == 0:
        str_temp += "There are no {}. ".format(func)
      elif len(values) == 1:
        str_temp += "{} is a {}. ".format(values[0], func)
      else :
        values_str = ""
        for str_val in values[:-1]:
          values_str += str_val + ", "
        str_temp += "{}and {} are {}. ".format(values_str, values[-1], func)

    elif func in verbs:

      if len(values) == 0:
        str_temp += "No one {} anyone. ".format(func)
      elif len(values) == 1:
        str_temp += "{} {} {}.".format(values[0][0], func, values[0][1])
      else :
        subj = {}
        for (v_1, v_2) in values:
          if v_1 not in subj:
            subj[v_1] = [v_2]
          else :
            subj[v_1].append(v_2)


        for sub in subj:
          values_str = ""
          if len(subj[sub]) == 1:
            str_temp += "{} {} {}.".format(sub, func, subj[sub][0])
          else :
            for val in subj[sub][:-1]:
              values_str += val + ", "
            str_temp += "{} {} {}and {}.".format(sub, func, values_str, subj[sub][-1])



  str_model = str_temp.replace(", and ", " and ")
  return str_model

def generate_datapoint(count_professions, verbs_set, names, domain_size = 5, signature_size = 4, max_count = 100, label = "random"):

  domain = random.sample(names, random.randrange(2, domain_size))
  #domain = random.sample(names, domain_size)
  #nouns = random.sample(count_professions, random.randrange(2, signature_size + 2))
  nouns = random.sample(count_professions, signature_size)
  #vbs = random.sample(verbs_set, random.randrange(1, signature_size))
  vbs = random.sample(verbs_set, signature_size)

  logic, sentence = generate_sentence_transitive_verbs(nouns, vbs, domain)

  signature_n = nouns.copy()
  signature_v = vbs.copy()

  model_found = False
  model = None
  
  if label == "random":
    label = random.choice([True, False])
  counter = 0
  model_nl = None
  while(True):
    model = model_generation(domain, signature_n, signature_v)

    val = nltk.Valuation(model)
    dom = val.domain
    m = nltk.Model(dom, val)
    g = nltk.sem.Assignment(dom)

    validity = m.evaluate(logic, g)

    if validity == label:
      model_found = True
      model_nl = model_to_nl(model, nouns, vbs, domain)
      break
    elif counter > max_count:
      break
    counter += 1

  return logic, sentence, model, label, model_found, model_nl

def generate_data(count_professions, verbs, names, domain_size = 5, signature_size = 7, max_count = 100, num_data_points = 100000):
  data = {
      'model' : [],
      'model_nl' : [],
      'sentence' : [],
      'logic' : [],
      'label' : []
  }

  count = 0
  model_not_found = 0

  count_false = 0
  count_truth = 0
  label = "random"
  while(count < num_data_points):
    logic, sentence, model, label, model_found, model_nl = generate_datapoint(count_professions, verbs, names, domain_size, signature_size, max_count, label)

    if (model_nl == None) or ("There are no" in model_nl) or ("No one" in model_nl):
      model_not_found += 1
      continue
    
    else:
      if model_found :
        data['model'].append(model)
        data['sentence'].append(sentence)
        data['logic'].append(logic)
        data['label'].append(label)
        data['model_nl'].append(model_nl)
        count += 1
        if label == False:
          count_false += 1
        else :
          count_truth += 1
        

        if count_false >= num_data_points/2:
          label = True
        elif count_truth >= num_data_points/2:
          label = False
        else :
          label = "random"
      else :
        model_not_found += 1
    if (count % 20000) == 0 :
      print("{} data points are generated".format(count))
  
  print("Number of times model did not generated: {}".format(model_not_found))

  df = pd.DataFrame(data)
  df['model'] = df['model'].astype(str)
  df = df.drop_duplicates(subset = ['sentence', 'model'], keep = 'first')

  return df

In [ ]:
df = generate_data(roles, verbs, names, num_data_points=40000)

20000 data points are generated
40000 data points are generated
Number of times model did not generated: 67931

In [ ]:
df['model_nl'].str.split().apply(len).max()

188

In [ ]:
df['model_nl'].str.split().apply(len).mean()

201.0439

In [ ]:
df.label.value_counts()

True     300000
False    300000
Name: label, dtype: int64

In [ ]:
df.head(10)

,model,model_nl,sentence,logic,label
0,"[('Lylah', 'Lylah'), ('Nasir', 'Nasir'), ('Esm...","Lylah, Nasir and Esmeralda are people in the g...",no non-cashier mention any non-secret_agent,all x.(-cashier(x) -> all y.(-secret_agent(y) ...,True
1,"[('Fabian', 'Fabian'), ('Lorelei', 'Lorelei'),...","Fabian, Matthias and Lorelei are people in the...",some queen approach no non-guest,exists x.(queen(x) & exists y.(-guest(y) & -ap...,True
2,"[('Laila', 'Laila'), ('Adley', 'Adley'), ('Van...","Laila, Adley, Neil and Vanessa are people in t...",some veterinarian need some non-economist,exists x.(veterinarian(x) & exists y.(-economi...,False
3,"[('Darwin', 'Darwin'), ('Emmitt', 'Emmitt'), (...",Darwin and Emmitt are people in the group. Dar...,all settler need Emmitt,"all x.(settler(x) -> need(x, Emmitt))",False
4,"[('Patrick', 'Patrick'), ('Addilyn', 'Addilyn'...","Addilyn, Alijah and Patrick are people in the ...",some driller surprise every non-surgeon,exists x.(driller(x) & all y.(-surgeon(y) -> s...,False
5,"[('Vicente', 'Vicente'), ('Barrett', 'Barrett'...","Israel, Vicente, Elina and Barrett are people ...",Vicente does not fight all data_scientist,"all x.(data_scientist(x) -> -fight(Vicente, x))",True
6,"[('Ezequiel', 'Ezequiel'), ('Denver', 'Denver'...",Denver and Ezequiel are people in the group. D...,some non-director like all non-judge,exists x.(-director(x) & all y.(-judge(y) -> l...,True
7,"[('Isla', 'Isla'), ('Fatima', 'Fatima'), ('Jos...","Elian, Isla, Joshua and Fatima are people in t...",a non-computer_scientist forgive every non-pla...,exists x.(-computer_scientist(x) & all y.(-pla...,False
8,"[('Walker', 'Walker'), ('Paige', 'Paige'), ('S...","Paige, Walker and Shiloh are people in the gro...",all judge investigate a non-floral_designer,all x.(judge(x) -> exists y.(-floral_designer(...,True
9,"[('Wilder', 'Wilder'), ('Harley', 'Harley'), (...","Harley, Ibrahim and Wilder are people in the g...",all blogger see every non-stunt_performer,all x.(blogger(x) -> all y.(-stunt_performer(y...,True

In [ ]:
df = df.sample(frac = 1)

df.label.value_counts()

True     300000
False    300000
Name: label, dtype: int64

In [ ]:
df.sample(10)

,model,model_nl,sentence,logic,label
46688,"[('Griffin', 'Griffin'), ('Emilee', 'Emilee'),...","Alyssa, Griffin, Emilee and Briana are people ...",every non-prisoner feel every cfo,all x.(-prisoner(x) -> all y.(cfo(y) -> feel(x...,False
591496,"[('Dariel', 'Dariel'), ('Estelle', 'Estelle'),...","Daleyza, Valentina, Estelle and Dariel are peo...",all non-reacher perceive all butler,all x.(-reacher(x) -> all y.(butler(y) -> perc...,True
371720,"[('Azalea', 'Azalea'), ('Graham', 'Graham'), (...","Azalea, Graham, Kathryn and Tiana are people i...",a non-cook does not eat every non-animal_breeder,exists x.(-cook(x) & all y.(-animal_breeder(y)...,True
549968,"[('Colin', 'Colin'), ('Greyson', 'Greyson'), (...","Colin, Greyson and Kyree are people in the gro...",no real_estate_agent investigate every cfo,all x.(real_estate_agent(x) -> exists y.(cfo(y...,True
374699,"[('Landyn', 'Landyn'), ('Ruby', 'Ruby'), ('peo...",Ruby and Landyn are people in the group. Ruby ...,some wrestler promise no librarian,exists x.(wrestler(x) & exists y.(librarian(y)...,False
179497,"[('Travis', 'Travis'), ('Ronan', 'Ronan'), ('A...","Addilynn, Ronan and Travis are people in the g...",a non-host does not shoot Addilynn,"exists x.(-host(x) & -shoot(x, Addilynn))",True
437749,"[('Emani', 'Emani'), ('Reagan', 'Reagan'), ('J...","Juliet, Emani and Reagan are people in the gro...",Reagan does not investigate every non-wrestler,"all x.(-wrestler(x) -> -investigate(Reagan, x))",True
298043,"[('Emilia', 'Emilia'), ('Brody', 'Brody'), ('p...",Brody and Emilia are people in the group. Brod...,no non-astronomer desire every non-plumber,all x.(-astronomer(x) -> exists y.(-plumber(y)...,True
271405,"[('Layla', 'Layla'), ('Ariana', 'Ariana'), ('A...","August, Layla and Ariana are people in the gro...",some non-dentist desire no copy_editor,exists x.(-dentist(x) & exists y.(copy_editor(...,False
336345,"[('Leilani', 'Leilani'), ('Ximena', 'Ximena'),...","Leilani, Ximena, Ephraim and Jaziel are people...",no warlord advise every photographer,all x.(warlord(x) -> exists y.(photographer(y)...,False

In [ ]:
df.drop_duplicates(subset = ['sentence', 'model_nl'], keep = 'first')

,model,model_nl,sentence,logic,label
590062,"[('Alexa', 'Alexa'), ('Gabriella', 'Gabriella'...","Atlas, Alexa, Andrew and Gabriella are people ...",no scorer forgive Alexa,"all x.(scorer(x) -> -forgive(x, Alexa))",True
159983,"[('Carly', 'Carly'), ('Julian', 'Julian'), ('B...","Cole, Blake, Julian and Carly are people in th...",some non-judge investigate Julian,"exists x.(-judge(x) & investigate(x, Julian))",False
396156,"[('Cynthia', 'Cynthia'), ('Sutton', 'Sutton'),...","Cynthia, Alma, Juliana and Sutton are people i...",some non-gymnast do not recognize all non-stra...,exists x.(-gymnast(x) & all y.(-stratergist(y)...,False
257060,"[('Musa', 'Musa'), ('Elaine', 'Elaine'), ('Dev...","Devon, Musa and Elaine are people in the group...",some lecturer draw all non-electrician,exists x.(lecturer(x) & all y.(-electrician(y)...,True
507402,"[('Antonella', 'Antonella'), ('Jacob', 'Jacob'...","Forest, Jacob and Antonella are people in the ...",no non-real_estate_agent kill any technician,all x.(-real_estate_agent(x) -> all y.(technic...,True
...,...,...,...,...,...
502366,"[('Athena', 'Athena'), ('August', 'August'), (...",August and Athena are people in the group. Ath...,all baby promise Athena,"all x.(baby(x) -> promise(x, Athena))",False
343868,"[('Tatum', 'Tatum'), ('Scarlett', 'Scarlett'),...","Tatum, Zuri and Scarlett are people in the gro...",some taxi_driver tolerate no non-ai_scientist,exists x.(taxi_driver(x) & exists y.(-ai_scien...,False
368711,"[('Duke', 'Duke'), ('Chance', 'Chance'), ('Ayd...","Chance, Paityn, Aydin and Duke are people in t...",a ceo hit some witch,exists x.(ceo(x) & exists y.(witch(y) & -hit(x...,False
201897,"[('Allan', 'Allan'), ('Kamiyah', 'Kamiyah'), (...","Maverick, Allan and Kamiyah are people in the ...",no non-scholar admire every barber,all x.(-scholar(x) -> exists y.(barber(y) & -a...,False
112182,"[('Winter', 'Winter'), ('Eloise', 'Eloise'), (...","Eloise, Tinley, Bennett and Winter are people ...",Eloise shoot all attacker,"all x.(attacker(x) -> shoot(Eloise, x))",False

In [ ]:
from sklearn.model_selection import train_test_split

df = df.sample(frac = 1)

train, test = train_test_split(df, test_size=100000, random_state=42)
train.reset_index(drop = True, inplace = True)
test.reset_index(drop = True, inplace = True)
df_100k = train.sample(100000)

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/My Drive/PhD/Model Checking')
%ls

all_fragments_1M_test_v1.csv
all_fragments_1M_train_v1.csv
all_fragments_500k_train_v1.csv
anaphora_100k_test_v2.csv
anaphora_100k_test_v3.csv
anaphora_100k_test_v4.csv
anaphora_100k_train_v2.csv
anaphora_100k_train_v3.csv
anaphora_100k_train_v4.csv
anaphora_1K_diag.csv
anaphora_40K_diag_1.csv
anaphora_40K_diag.csv
anaphora_40k_t1.csv
anaphora_40k_test_domain_5.csv
anaphora_40k_test_domain_6.csv
anaphora_40k_test_domain_7.csv
anaphora_40k_test_domain_8.csv
anaphora_40k_test_domain_9.csv
anaphora_40k_test_predicate_1.csv
anaphora_40k_test_predicate_2.csv
anaphora_40k_test_predicate_3.csv
anaphora_40k_test_predicate_4.csv
anaphora_500k_train_v2.csv
anaphora_500k_train_v3.csv
anaphora_500k_train_v4.csv
BERT/
relative_clauses_syllogistic_100k_test_v2.csv
relative_clauses_syllogistic_100k_test_v3.csv
relative_clauses_syllogistic_100k_test_v4.csv
relative_clauses_syllogistic_100k_test_v5.csv
relative_clauses_syllogistic_100k_train_v2.csv
relative_clauses_syllogistic_100k_train_v3.csv
relative_clauses_syllogistic_100k_train_v4.csv
relative_clauses_syllogistic_500k_train.csv
relative_clauses_syllogistic_500k_train_v2.csv
relative_clauses_syllogistic_500k_train_v3.csv
relative_clauses_syllogistic_500k_train_v4.csv
relative_clauses_syllogistic_500k_train_v5.csv
relative_transitive_verbs_100k_test_v1.csv
relative_transitive_verbs_100k_test_v2.csv
relative_transitive_verbs_100k_test_v3.csv
relative_transitive_verbs_100k_test_v4.csv
relative_transitive_verbs_100k_test_v5.csv
relative_transitive_verbs_100k_test_v6.csv
relative_transitive_verbs_100k_test_v7.csv
relative_transitive_verbs_100k_test_v8.csv
relative_transitive_verbs_100k_test_v9.csv
relative_transitive_verbs_100k_train_v6.csv
relative_transitive_verbs_100k_train_v7.csv
relative_transitive_verbs_100k_train_v8.csv
relative_transitive_verbs_500k_train_v5.csv
relative_transitive_verbs_500k_train_v6.csv
relative_transitive_verbs_500k_train_v7.csv
relative_transitive_verbs_500k_train_v8.csv
relative_transitive_verbs_500k_train_v9.csv
syllogistic_100k_test_v7.csv
syllogistic_100k_test_v8.csv
syllogistic_100k_train_domain_5.csv
syllogistic_100k_train_v7.csv
syllogistic_500k_train_v7.csv
syllogistic_500k_train_v8.csv
syllogistic_domain_6.csv
syllogistic_domain_7.csv
syllogistic_test_domain_5.csv
syllogistic_test_domain_6.csv
syllogistic_test_domain_8.csv
syllogistic_test_pred_10.csv
syllogistic_test_pred_12.csv
syllogistic_test_pred_9.csv
T5/
test_trainer/
transitive_verbs_100k_test_v10.csv
transitive_verbs_100k_test_v7.csv
transitive_verbs_100k_test_v8.csv
transitive_verbs_100k_test_v9.csv
transitive_verbs_100k_train_v10.csv
transitive_verbs_100k_train_v9.csv
transitive_verbs_500k_train_v10.csv
transitive_verbs_500k_train_v7.csv
transitive_verbs_500k_train_v8.csv
transitive_verbs_500k_train_v9.csv

In [ ]:
train.to_csv('transitive_verbs_500k_train_v10.csv', index=False)

In [ ]:
test.to_csv('transitive_verbs_100k_test_v10.csv', index=False)

In [ ]:
df = df.sample(frac = 1)

df.to_csv('transitive_verbs_test_pred_12.csv', index=False)

In [ ]:
train.label.value_counts()

False    250025
True     249975
Name: label, dtype: int64

In [ ]:
det_dict = {'all' : {True : 0, False : 0},
            'a' : {True : 0, False : 0},
            'some' : {True : 0, False : 0},
            'every' :{True : 0, False : 0}}

quantifier_dict = {'all' : {True : 0, False : 0},
                   'exists' : {True : 0, False : 0}}




for index, row in df.iterrows():
  det = row['sentence'].split()[0]
  quantifier = row['logic'].split()[0]

  if (det in det_dict) and (row['sentence'].split()[-2] in det_dict) :
    det_dict[det][row['label']] += 1
    quantifier_dict[quantifier][row['label']] += 1


det_dict

{'a': {False: 18588, True: 18590},
 'all': {False: 18824, True: 18777},
 'every': {False: 18592, True: 18583},
 'some': {False: 18943, True: 18994}}

In [ ]:
quantifier_dict

{'all': {False: 14105, True: 14033}, 'exists': {False: 9213, True: 9545}}

In [ ]:
#df['model'] = df['model'].astype(str)

df.drop_duplicates(subset = ['sentence', 'model_nl'], keep = 'first')

                                                    model  ...  label
0       [('Blair', 'Blair'), ('Xiomara', 'Xiomara'), (...  ...   True
1       [('Alannah', 'Alannah'), ('Penny', 'Penny'), (...  ...  False
2       [('Kieran', 'Kieran'), ('Nellie', 'Nellie'), (...  ...   True
3       [('Alvaro', 'Alvaro'), ('Opal', 'Opal'), ('Alo...  ...   True
4       [('Nelson', 'Nelson'), ('Cannon', 'Cannon'), (...  ...  False
...                                                   ...  ...    ...
199995  [('Kenneth', 'Kenneth'), ('Otis', 'Otis'), ('A...  ...  False
199996  [('Rayan', 'Rayan'), ('Mekhi', 'Mekhi'), ('Ben...  ...   True
199997  [('Jair', 'Jair'), ('Leo', 'Leo'), ('people', ...  ...   True
199998  [('Langston', 'Langston'), ('Nadia', 'Nadia'),...  ...  False
199999  [('Itzayana', 'Itzayana'), ('Jabari', 'Jabari'...  ...  False

[200000 rows x 5 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/My Drive/PhD/Model Checking')
%ls

template_based_syllogistic_200k_nl.csv

In [ ]:
df.to_csv('template_based_transitive_200k_nl.csv', index=False)

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('template_based_transitive_200k_nl.csv', error_bad_lines=False)
df

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

                                                    model  ...  label
0       [('Blair', 'Blair'), ('Xiomara', 'Xiomara'), (...  ...   True
1       [('Alannah', 'Alannah'), ('Penny', 'Penny'), (...  ...  False
2       [('Kieran', 'Kieran'), ('Nellie', 'Nellie'), (...  ...   True
3       [('Alvaro', 'Alvaro'), ('Opal', 'Opal'), ('Alo...  ...   True
4       [('Nelson', 'Nelson'), ('Cannon', 'Cannon'), (...  ...  False
...                                                   ...  ...    ...
199995  [('Kenneth', 'Kenneth'), ('Otis', 'Otis'), ('A...  ...  False
199996  [('Rayan', 'Rayan'), ('Mekhi', 'Mekhi'), ('Ben...  ...   True
199997  [('Jair', 'Jair'), ('Leo', 'Leo'), ('people', ...  ...   True
199998  [('Langston', 'Langston'), ('Nadia', 'Nadia'),...  ...  False
199999  [('Itzayana', 'Itzayana'), ('Jabari', 'Jabari'...  ...  False

[200000 rows x 5 columns]

In [ ]:
df.tail(5)

                                                    model  ...  label
199995  [('people', {'Turner', 'Lionel', 'Emir', 'Joyc...  ...  False
199996  [('people', {'Cohen', 'Jermaine', 'Legend', 'H...  ...   True
199997  [('people', {'Bianca', 'Estrella'}), ('cleaner...  ...   True
199998  [('people', {'Dominick', 'Molly', 'Aliza', 'Al...  ...   True
199999  [('people', {'Juliana', 'Lailah'}), ('soldier'...  ...   True

[5 rows x 4 columns]

### Testing model checking function

In [ ]:
generate_datapoint(count_professions, emotion_adj, names)

['Berkley', 'Anais'] ['epidemiologist', 'optician', 'archeologist'] ['Gloomy', 'Mysterious']
['optician', 'archeologist']
a Noun ['optician', 'archeologist'] {'optician': False, 'archeologist': True}

('exists x.(optician(x) & -archeologist(x))',
 'a optician is not a archeologist',
 [('people', {'Anais', 'Berkley'}),
  ('epidemiologist', {'Anais', 'Berkley'}),
  ('optician', {'Berkley'}),
  ('archeologist', {'Anais'}),
  ('Gloomy', set()),
  ('Mysterious', {'Berkley'})],
 True,
 True)

In [ ]:
>>> import nltk
>>> from nltk.sem import Valuation, Model
v = [('adam', 'b1'), ('betty', 'g1'), ('fido', 'd1'),
... ('girl', set(['g1', 'g2'])), ('boy', set(['b1', 'b2'])),
... ('dog', set()),
... ('love', set([('b1', 'g1'), ('b2', 'g2'), ('g1', 'b1'), ('g2', 'b1')]))]

>>> val = Valuation(v)
>>> dom = val.domain
>>> m = Model(dom, val)

>>> dom = val.domain
>>> g = nltk.sem.Assignment(dom)
>>> m.evaluate('all x.(dog(x) -> love(x, betty))', g)

True

In [ ]:
template_syllogistic("neg_noun_adj_si"]

SyntaxError: ignored

In [ ]:
str_temp = ""

for i in v:
  func = i[0]
  values = list(i[1])
  print(values)

  if func == "people":
    values_str = ""
    for str_val in values[:-1]:
      values_str += str_val + ", "
    
    str_temp += "{}and {} are people in the group. ".format(values_str, values[-1])
  else :
    if len(values) == 0:
      str_temp += "There are no {}. ".format(func)
    elif len(values) == 1:
      str_temp += "{} is a {}. ".format(values[0], func)
    else :
      values_str = ""
      for str_val in values[:-1]:
        values_str += str_val + ", "
      str_temp += "{}and {} are {}. ".format(values_str, values[-1], func)

  str_temp = str_temp.replace(", and ", " and ")

['Khaleesi', 'Ellison', 'Joziah', 'Kaiser']
['Khaleesi', 'Joziah', 'Ellison']
['Khaleesi', 'Kaiser']
['Joziah']
['Khaleesi', 'Joziah', 'Kaiser']
['Khaleesi']
[]

In [ ]:
str_temp

'Khaleesi, Ellison, Joziah and Kaiser are people in the group. Khaleesi, Joziah and Ellison are machinist. Khaleesi and Kaiser are engineer. Joziah is a driller. Khaleesi, Joziah and Kaiser are Safe. Khaleesi is a Earnest. There are no Supportive. '